### ISSUE TITLE
when kubelet unable to read config file - virtlet don't undefine VM from libvirt

### ISSUE THREAD

**Issue by levor23** [Mirantis/virtlet#115]
commit f4c985b862f2fb7e442af8db351151e9b60a43fc
Merge: 9c1d32a ab3f861
Author: Piotr Skamruk <piotr.skamruk@gmail.com>
Date:   Tue Nov 15 09:03:30 2016 +0100

    Merge pull request #114 from Mirantis/ivan4th/fix-k8s-version-pinning
    
    Fix k8s version pinning

In case of losing config file for pod  need to execute next scenario:
 
1)Shutdown domain
2)Undefine domain
3)Remove created boot image/snapshot
4)Remove created volumes
5)Clean virtlet internal pod info

but we have only step1 executed:
kubelet logs
http://paste.openstack.org/show/589562/

docker exec -it dockercompose_libvirt_1 virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     test-vm-cirros                 shut off

docker exec -it dockercompose_libvirt_1 virsh vol-list default
 Name                 Path                                    
------------------------------------------------------------------------------
 cirros-0.3.4-x86_64-disk.img /var/lib/libvirt/images/cirros-0.3.4-x86_64-disk.img

also I don't understand how config file is tracked

example:
_sudo kubernetes/server/kubernetes/server/bin/kubelet --container-runtime-endpoint=/run/virtlet.sock --image-service-endpoint=/run/virtlet.sock --config=/home/vagrant/test.yaml > /tmp/kubelog 2>&1_

I tried to move test.yaml to /tmp/test.yaml - nothing changed, all worked.
I tried to move /tmp/test.yaml /tmp/test2.yaml
And when test2.yaml was removed - Only then I recieve "unable to read config path "/home/vagrant/test.yaml" in kubelet log.
And path in log message was incorrect.

**Comment by jellonek** [comment]
Domain undefine/removal/cleanup is called after kubelet call PodStandboxRemove, which is called not directly after pod stopping procedure, but after some period, during periodical garbage collection (afair ~2-5min. after stopping POD).

So imo this issue is invalid, as whole procedure is called, but we have to wait for it a bit.
