### ISSUE TITLE
XML handling

### ISSUE THREAD

**Issue by jellonek** [Mirantis/virtlet#132]
We should stop rely on plain string templates for domain XML generation. Instead we should fill initial values in structs, operate on them and only once at the end generate from this XML, cutting down need to parse it at first.

So this is placeholder issue for future refactor.

**Comment by vefimova** [comment]
As a follow-up of libvirt GO bindings there has come up another project with libvirt Go XML parser from the same author: https://github.com/libvirt/libvirt-go-xml. I think, this will be the answer to our XML handling issue.

------------------------------------------------------------
Other options which may be tried just in case
1. Automatically convert libvirt domain description (http://libvirt.org/schemas/) to go structs, using 
   - https://github.com/gnewton/chidley  converts any XML to Go structs (and therefor to JSON)
   - https://github.com/metaleap/go-xsd
2. Use XPATH-like access  launchpad.net/xmlpath (https://godoc.org/gopkg.in/xmlpath.v1)
3. Use DOM-like style, requires CGO (like Nokogiri - ruby-based) https://github.com/moovweb/gokogiri - LibXML bindings for the Go programming language.
