### ISSUE TITLE
"User-friendly" Makefile

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#137]
Add Makefile that can be used to build virtlet using virtlet_build container, run tests (unit/integration/e2e) and local environment.

Move Makefile.am and other autotools stuff to build/ so as to avoid confusion,

**Comment by jellonek** [comment]
Actual makefile permits much faster local compilation (i'm using it as syntax check) so maybe we can add leave current way of compilation under some additional-not default targets?

**Comment by lukaszo** [comment]
No plans for it. `build/cmd.sh` is used instead
