### ISSUE TITLE
Use alpine image for e2e

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#142]
Cirros image that's used currently spends a lot of time trying to reach cloud-init server

**Comment by jellonek** [comment]
We need to prepare own image for alpine, because it only have .iso image for installation.
This .iso can be booted as disk image, but I didn't check if it setups network with dhcp by default.
 
So if we will use own image - also we will need to host it somewhere.

**Comment by jellonek** [comment]
We get used to use cirros, so i'm closing this one as having a very low priority. It can be reopened when its priority would increase.
