### ISSUE TITLE
Clean libvirt state & restart libvirt between integration tests

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#168]
In case we decide to keep libvirt, we need to have it cleaned up & restarted between integration tests. They work w/o such cleanup for now, but strictly speaking that's incorrect.

**Comment by jellonek** [comment]
Maybe adding `LIBVIRT_CLEANUP=true` to container env will be a good start for this? This can help a bit developer using these tests locally, but still this does not provide a cleanup between particular tests, only between whole test suite invocation.
