### ISSUE TITLE
Get DNS config from PodSandboxConfig.DNSConfig in RunPodSandbox

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#191]
That's how docker-shim works and we should do it, too.
What needs to be clarified: what takes precedence if both CNI and PodSandboxConfig include DNS settings. Or we should merge these?

**Comment by jellonek** [comment]
This is good question to sig network. In theory this should be consistent and operator should set this to same value, but if I would design that - I would expect that value from PodSandboxConfig have a higher priority.
