### ISSUE TITLE
Don't access kubelet's /configz directly during CRI proxy bootstrap

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#193]
Kubelet's https server on port 10250 may be secured in some installations. Get node name via port `http://localhost:10255/stats/summary` first (we're already doing this anyway) and then use apiserver proxy functionality to grab `/configz`. [Example here](https://github.com/kubernetes/kubernetes/blob/v1.5.2/test/e2e_node/util.go#L146).

**Comment by jellonek** [comment]
Outdated. Criproxy is already moved to a separate project.
