### ISSUE TITLE
Auto-modify apiserver configuration during virtlet setup on kubeadm clusters

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#194]
The following options need to be added to apiserver config:
`--feature-gates=StreamingProxyRedirects=true --feature-gates=DynamicKubeletConfig=true`
This can be done by a `Job` residing in the same `.yaml` file as Virtlet DaemonSet. It should also mark the cluster as 'ready for virtlet' somehow (maybe there's a cluster-wide way to query API server settings?) and Virtlet init containers that are responsible for CRI proxy bootstrap must wait for it before starting.

**Comment by jellonek** [comment]
Looks like outdated issue. If it's still relevant - please reopen it.
