### ISSUE TITLE
Unikernel experiment

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#208]
Try to run unikernel images on Virtlet.
Demonstrate the ability of unikernel application to access cluster networks, utilize services etc.
For more info see kubernetes/kubernetes#25885

**Comment by miha-plesko** [comment]
I'm running OSv unikernel using virtlet and it works pretty well so far 👍 
What I'm missing very much, however, is ability to see what unikernel writes into console:

```bash
$ kubectl logs my-vm-pod
failed to open log file "/var/log/pods/52b85f47-12cc-11e7-9c2e-02420ac00002/_0.log": open /var/log/pods/52b85f47-12cc-11e7-9c2e-02420ac00002/_0.log: no such file or directory
```

I've tried to connect to `virtlet` container and examine logs in `/var/log/libvirt/qemu/` folder. But the logs there are provided only up until VM/unikernel starts. Then if I do `virsh console <...>`, I get connection to the VM's console, but can't see what was printed there when VM started.


@ivan4th am I perhaps missing something, or is this yet to be implemented?

**Comment by jellonek** [comment]
We don't have any support for logs, but I see there one possibility - we can add as option archiving output sent to serial console. This sets requirements on workload side, but should work if we would use it with http://www.conserver.com/

**Comment by pigmej** [comment]
Closing that, since both unikernel and logs are done (some imporvements needed but let's close that issue).
