### ISSUE TITLE
Respect `imagePullPolicy` for VMs

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#228]
I'm working on DIND cluster that is set up with:
```bash
./demo.sh
```
There is `image-server` pod that serves QCOW2 images to `virtlet` daemon pod. Everything works fine, but if you update QCOW2 image inside `image-server` (folder /usr/share/nginx/html/), the update is not reflected on virtlet daemon. In fact, I can delete QCOW2 image from `image-server` and virtlet daemon can still spawn new pods based on this image 😅 

Does virtlet daemon cache images somewhere? Is it possible to disable caching?

**Comment by jellonek** [comment]
Image server in example is only for demo purpose. It's really not needed, you can use in pod definition any http accessible resource (http, https is planned for next 2 weeks).

Image after downloading by http is stored in local store (to be more precise, in libvirt store), just like docker images are stored in docker registry.
That's true that we don't have yet support for `imagePullPolicy` - it's a bug and hopefully will be quickly fixed.

**Comment by miha-plesko** [comment]
Thanks for the answer @jellonek. Do you perhaps know how can I manually remove downloaded image from libvirt store? I'm able to connect to image-server container, but what to delete there? I queried
```bash
virsh vol-list volumes
```
but the volumes listed here seems to get deleted when qemu-system process exits.

**Comment by miha-plesko** [comment]
Found it, it's `/var/lib/libvirt/images/`, thank you so much!

**Comment by jellonek** [comment]
Yeah, it's in different pool. `virsh pool-list` will show you which are configured and we have two of them, `volumes` (pointing to `/var/lib/virtlet`) for storing disk drives generated for use as volumes, and `default` (pointing to mentioned `/var/lib/libvirt/images/`) which should contain VM images used to create snapshot disk, from which VM will be booted.

So now preferred method to "cleanup" old images is to use `virsh vol-delete --pool default image_name`. As we don't store any additional metadata for volumes in libvirt - also it could be safe to `rm` file directly from directory, but for future - it should be safer to use `virsh` for that ;)
