### ISSUE TITLE
Cannot boot Ubuntu 16.10 Server VM on virtlet

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#231]
I'm trying to run my own VM on Kubernetes using Virtlet and everything is green and the "Running" status is reported:

![capture](https://cloud.githubusercontent.com/assets/8102426/24602851/d9482a9a-185e-11e7-9e03-51cd1f8f0602.PNG)

But then I can't find a way to connect to the VM. Neither `virsh console` nor `ssh` seems to be working. Both methods work for cirros image, though.

#### What did I try
I've created a new QCOW2 and installed Ubuntu Server 16.10 on it. Inside Ubuntu I've enabled ssh server and ttyS0. Then I run it on virtlet and try to connect like this:
```bash
$ kubectl exec -it virtlet-9l1fz -n kube-system -- /bin/bash -c "virsh list"
Id    Name                           State
----------------------------------------------------
 1     aa65799e-59f4-4cd6-6943-672f1b02c5fa-cirros-vm running
 11    cefc0eda-f400-4c45-5599-7abdb748e122-miha-ubuntu-server running

$ kubectl exec -it virtlet-9l1fz -n kube-system -- /bin/bash -c "virsh console 11"
Connected to domain cefc0eda-f400-4c45-5599-7abdb748e122-miha-ubuntu-server
Escape character is ^]
# nothing happens when I press keys
```

But I cannot access the VM from anywhere. If I dump libvirt XML and run it on my host, changing nothing but qcow2 image path and removing `<emulator>/vmwrapper</emulator>`, everything works:
```bash
<virtlet>$ virsh dumpxml 11 >./ubuntu_server_dump.xml
<host>   $ virsh create ./ubuntu_server_dump.xml --console
# the login prompt appears as expected
```

Any idea on how to debug/fix this? The QCOW2 image that I'm trying to run is available [here](http://x.k00.fr/ubuntu) with credentials `ubuntu | pass`. I'm really lost on this one since it feels like everything should be working with no problems.

**Comment by miha-plesko** [comment]
Alternatively, do you perhaps own an image that runs well on virtlet (and has `apt-get` available) that you could share?

**Comment by jellonek** [comment]
Sorry for not responding earlier.
This can be connected with two things:
* ubuntu image is not prepared to have console on serial port (quite normal)
* it's prepared to configure itself using cloud init metadata server - which we don't support yet right now.

We have a plan to support at last cloud init config drive to eliminate/reduce later issue. Also we have planned research on how to support vnc console, so this should solve no-output which is a part of second issue.

I'll also test mentioned image by myself, probably tomorrow morning.

**Comment by miha-plesko** [comment]
Thank you for [fixing this](https://github.com/Mirantis/virtlet/commit/0de5e5d4deb04256bf14cce4803c15bb9d066a7e). I am now able to run ubuntu server and connect to it using virsh console.

I am not able to ssh yet, but I think it's not an issue with Virtlet but with networking configuration in guest OS. Closing the issue.

**Comment by miha-plesko** [comment]
Ah, I just managed to SSH as well - it was a problem with guest OS indeed. Adding this comment just for a future reference:

I had to update `/etc/network/interfaces` so that it contains:
```
allow-hotplug ens6
iface ens6 inet dhcp
```
and then run:
```bash
$ sudo ifup ens6
```
