### ISSUE TITLE
Performance drop when accessing VM from another VM

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#237]
I'm running two VMs on virtlet, one with MySQL database and one with NodeJS frontend and I've noticed a huge network performance drop when they communicate with each other. Below please find a screenshot of frontend VM that needs **8.13s** to render page because of slow MySQL connection:

![capture](https://cloud.githubusercontent.com/assets/8102426/24654971/71a0d804-193c-11e7-9df3-ed9641a1e66d.PNG)

Running the frontend VM from host directly (but still connecting to the very same MySQL VM that runs on virtlet) renders page smoothly in **624ms**:

![capture](https://cloud.githubusercontent.com/assets/8102426/24655201/8d8583a2-193d-11e7-9683-aca53ad354d5.PNG)

So the problem seems to only exist in communication between two Virtlet-driven VMs. Do you perhaps know what could possibly cause such a latency?

# Two cirros images experiment
The networking performance problem can be reproduced with two cirros images as well. If you serve a file in the first cirros, it takes quite some time to download it in the second cirros.

First cirros serves file:
```bash
<cirros-1> $ # write "EVERYTHING IS AWESOME" in awesome.txt file 10k times
<cirros-1> $ echo "" > awesome.txt
<cirros-1> $ for i in `seq 0 1 10000`; do echo "${i}_EVERYTHING_IS_AWESOME" >> awesome.txt; done
<cirros-1> $ # serve the awesome.txt file on port 8000
<cirros-1> $ while true ; do nc -l -p 8000 < awesome.txt ; done
```
And second cirros accesses it:
```bash
<cirros-2> $ time curl 10.192.2.2:8000 # <--- this is IP of the first cirros
...
9998_EVERYTHING_IS_AWESOME
9999_EVERYTHING_IS_AWESOME
10000_EVERYTHING_IS_AWESOME

real	0m 4.92s # 5 seconds!
user	0m 0.08s
sys	0m 3.82s
```

And if I access the very same cirros, but from container:
```bash
$ kubectl run ubuntu-cont --image=ubuntu:16.04 -i --tty
<ubuntu-container> $  time curl 10.192.2.2:8000 # <--- this is IP of the first cirros
...
9998_EVERYTHING_IS_AWESOME
9999_EVERYTHING_IS_AWESOME
10000_EVERYTHING_IS_AWESOME

real	0m0.906s # less than one second
user	0m0.008s
sys	0m0.004s
```

Do you have any idea what could cause the networking problems *only* when two VMs communicate?

/cc @gberginc

**Comment by jellonek** [comment]
It could be because of https://github.com/Mirantis/virtlet/blob/master/deploy/virtlet-ds.yaml#L121 - can you remove this env variable from daemonset descripion, remove virtlet container (it should be restarted) and redo the test?

**Comment by miha-plesko** [comment]
Aint gonn be that easy, the KVM is already un-disabled :P

![capture](https://cloud.githubusercontent.com/assets/8102426/24656601/7a5d327e-1943-11e7-892e-dcc13ab5194b.PNG)

**Comment by ivan4th** [comment]
Please try removing this env var altogether, virtlet checks for an empty string. Sorry for the confusion.

**Comment by miha-plesko** [comment]
@jellonek @ivan4th thank you so much for your fast response. Enabling KVM did help significantly, the page shows up **instantly**. Everything is awesome, I like Virtlet so much 😄 

My team and myself are really looking forward to integrate OSv unikernels into Virtlet. You see, unikernels are hard to prepare and manage, but plugging them in Kubernetes (using Virtlet) fixes this problem. I would, if I may, ask you for a tip or two on how to proceed the integration. Would you be willing to give some advise? If possible, I'd schedule a video call with you and explain our plans. There I would ask you for a comment/advice. But if you prefer, I can open an issue and ask you there. Please let me know if there is any chance to get in touch with you guys.

**Comment by gberginc** [comment]
Great news @miha-plesko!

**Comment by jellonek** [comment]
@miha-plesko great to read this!
@pigmej will contact with you tomorrow regarding this video call.
