### ISSUE TITLE
Push changes in vmwrapper source to the DIND

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#266]
Is there a way to push changes made to vmwrapper to a running DIND cluster? What I'm trying is:
```bash
$ ./build/cmd.sh build
$ ./build/cmd.sh copy-dind
```
But the changes seem not to reflect on the cluster. I can, of course, use the following approach:
```bash
$ ./build/cmd.sh build
$ ./build/cmd.sh copy
$ docker build -t mirantis/virtlet .
$ INJECT_LOCAL_IMAGE=yes ./demo.sh
```
but that means I have to deploy whole cluster from scratch every time...

**Comment by ivan4th** [comment]
Does `.../dind-cluster-v1.6.sh up` and redeploying Virtlet DaemonSet help?

**Comment by ivan4th** [comment]
(after copy-dind)

**Comment by miha-plesko** [comment]
For some reason the virtlet daemonset then gets created with 0 pods. Not sure what he's missing or how to convince him to spawn a virtlet pod.

**Comment by ivan4th** [comment]
Sorry, forgot to mention that `extraRuntime=virtlet` label on target nodes.
You may apply it like this: `kubectl label node kube-node-1 extraRuntime=virtlet`
or just use `./build/cmd.sh start-dind`. The latter applies the label to the first node and then starts
the development version of daemonset (`deploy/virtlet-ds-dev.yaml`), which supports picking up updated binaries after `copy-dind` and also has KVM disabled by default so it can run on Mac Docker etc. (you may want to edit it to reenable KVM)

**Comment by miha-plesko** [comment]
Thanks @ivan4th, with your help I managed to resolve the problem. I'm posting steps here and closing an issue.

### How to update `virtlet` binary without destroying the cluster
To achieve this, one must modify virtlet container prior booting the cluster. Namely, one must replace [this line](https://github.com/Mirantis/virtlet/blob/master/image_skel/start.sh#L84) of `start.sh` script with following line:
```bash
sleep infinity
```
Then you raise DIND with `INJECT_LOCAL_IMAGE=yes ./deploy/demo.sh` and when cluster is actively waiting for CirrosOS VM to boot:
```bash
* Waiting for: CirrOS VM
........................................................
........................................................
..................................................
```
you connect to virtlet container and manually run `virtlet` binary in it:
```
$ kubectl exec -it virtlet-z6nr1 -n kube-system -- /bin/bash
root@kube-node-1:/#  /virtlet -v=3 -logtostderr=true -libvirt-uri=qemu+tcp://localhost/system -image-download-protocol=http &> /my-virtlet.log &
```
At this point you have a fully functional DIND cluster up-and-running and you are able to replace `/virtlet` binary at any time. To apply it, you just `kill -9` the previous ` /virtlet -v=3 -logtostderr=true...` process inside virtlet container and run it again with:
```bash
/virtlet -v=3 -logtostderr=true -libvirt-uri=qemu+tcp://localhost/system -image-download-protocol=http &> /my-virtlet.log &
```

### How to update `vmwrapper` binary without destroying the cluster
Since `vmwrapper` is a standalone program that is called on demand, you only need to replace the `/vmwrapper` file (inside virtlet container) with the new one.

### How to add debug logs to Virtlet's Go source
If you are unable to find your logs of vmwrapper (as I was), you can use following function in Go source instead of glog and fmt.Println():
```go
func logToFile(txt string, args ...interface{}) {
	FILE := "/tmp/debug-vmwrapper.log"

	if _, err := os.Stat(FILE); os.IsNotExist(err) {
		file, _ := os.Create(FILE)
		file.Close()
	}

	f, err := os.OpenFile(FILE, os.O_APPEND|os.O_WRONLY, 0777)
	if err != nil {
		fmt.Println("could not open file to log into:", err)
	}
	defer f.Close()

	if len(args) > 0 {
		txt = fmt.Sprintf(txt, args)
	}

	f.WriteString(txt + "\n")
}
```
The log is then always waiting for you inside a FILE in virtlet container 😄 


@ivan4th if you realize that any of the steps that I describe here is clumsy and can be achieved easier, please let me know!
