### ISSUE TITLE
Translate K8s Requests/Limits into "Domain Size"

### ISSUE THREAD

**Issue by maugustosilva** [Mirantis/virtlet#276]
Currently, new instances are always created with 1 GB of RAM and a number of vCPUs equals the total detected amount on the Host. I would like to propose a "translation" between K8s Requests/Limits and the "Domain size". An initial idea would be to start with a pod description definition like:

```...
  containers:
    - name: cirros-vm127
      image: virtlet/image-service/cirros
      resources:
        limits:
          memory: "4096Mi"
          cpu: "4"
```

And then have as the result a 4-vCPU, 4GB of RAM Domain. 

Internally, it could be implemented by simply dividing the (already obtained and used) cpuQuota and cpuPeriod, provided that these are non-zero. Similarly, the (also already obtained) MemoryLimitInBytes could be used to determine the Domain actual memory. In case these limits are not specified by the user, just default to what is already in place, as determined/discussed in https://github.com/Mirantis/virtlet/issues/67.

**Comment by pigmej** [comment]
Hey,

Thanks for reporting, this is already on our short term plans sadly it's not clearly visible in public. Both memory and CPU limits will be supported pretty soon (I'd say next week, really)

**Comment by ivan4th** [comment]
Hi, Virtlet supports vCPU count settings now. I've added [an example](https://github.com/Mirantis/virtlet/blob/master/examples/cirros-vm.yaml) of how to use CPU & memory settings in the pod definitions. [Here's](https://asciinema.org/a/4ubwirr4oaufa0kvc4yw5u0tp) an asciinema demo of these settings in action.

**Comment by maugustosilva** [comment]
Hello @pigmej, @ivan4th, thanks, I see it on the code now, as a Virtlet-specific annotation. 

Allow me to point out that this design choice, while perfectly valid and functional, has two characteristics that - IMHO - makes it less than desirable: 

a) it introduces yet another Virtlet-specific annotation (I truly believe that having VM-Pods that can be constructed with minimal differences from a "regular" Container-Pod is a plus) 

b) It is not clear to me what effect will it have on the actual K8s resource management/scheduler (my initial proposal, albeit far from perfect, did allow an user to signal, through K8s, the Domain Size, giving the K8s scheduler some ability to keep track of VM resources in an integrated manner)

Anyway, just my 2 cents. Keep up the fine work, this project is highly useful. Feel free to close the issue. Many thanks.

**Comment by jellonek** [comment]
The problem with "regular" cpu limit is that it can be specified as not only integer value, but e.g. "300m", which can not be directly transformed to vCPUs in virtual machine.
We are thinking how to resolve this issue, so this could be compatible with k8s resource management/scheduler.

I think that the simplest way to achieve this would be to support original cpus limits, but with only integer values, make it clear in documentation, and then fail at validation point when there will be request for non integer value.

So, I'm leaving this issue as open for now.

**Comment by ibmcb** [comment]
@jellonek Sure, thanks. I have an (admittedly, quite crude) implementation where I just round up `cpuQuota/cpuPeriod` to `1` in case the result is smaller than an unitary integer. So, if an user specifies a VM-Pod with something like `cpu: "250m"`, K8s will be informed that this Pod expects to take up to a 1/4th of a CPU, while (Virtlet-driven) Libvirt will create a domain with one whole vCPU (the implicit assumption is that four VM-Pods such as this would share a single pCPU). Again, not a perfect solution, but it would provide more information for both the K8s Scheduler and the user.

**Comment by maugustosilva** [comment]
@jellonek Sure, thanks. I have an (admittedly, quite crude) implementation where I just round up cpuQuota/cpuPeriod to 1 in case the result is smaller than an unitary integer. So, if an user specifies a VM-Pod with something like cpu: "250m", K8s will be informed that this Pod expects to take up to a 1/4th of a CPU, while (Virtlet-driven) Libvirt will create a domain with one whole vCPU (the implicit assumption is that four VM-Pods such as this would share a single pCPU). Again, not a perfect solution, but it would provide more information for both the K8s Scheduler and the user.

**Comment by jellonek** [comment]
Rounding seems better than custom annotations, but still I think that we should describe in docs that only integer values are expected, and we should inform about error if there is other definition. Explicit is better then implicit.

**Comment by jellonek** [comment]
Btw. #299 is a design proposal in this area.
