### ISSUE TITLE
Handle situation when unikernel stops (crashes)

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#285]
When doing a dry-run for today's presentation one of our unikernels crashed (some runtime error, not related to Virtlet I think). However, the error that I got from Virtlet was somewhat strange:

![capture](https://cloud.githubusercontent.com/assets/8102426/26354775/5df4c2ce-3fc6-11e7-9912-c517cf991c0f.PNG)

The unikernel was booted properly and crashed while operating due to mistake in application code:

![capture](https://cloud.githubusercontent.com/assets/8102426/26354810/8ef905d8-3fc6-11e7-980d-aa0c852dbd2f.PNG)

What I'd expect from Virtlet is to say "VM has stopped unexpectedly" instead of crashing with this error.

/cc @jellonek

**Comment by miha-plesko** [comment]
Why did our unikernel crash in runtime? -> It appears we haven't given it enough RAM. After increasing RAM from 256MB to 1GB everything seems to be working (I can deploy and redeploy application without any problems).

**Comment by ivan4th** [comment]
Ok, we'll fix VM crash handling in Virtlet.
