### ISSUE TITLE
Support both HTTP and HTTPS at the same time

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#292]
There is a [`VIRTLET_DOWNLOAD_PROTOCOL`](https://github.com/Mirantis/virtlet/blob/master/deploy/virtlet-ds.yaml#L102-L103) flag available to decide whether Virtlet should use SSL when downloading images or not.

I would appreciate this decision to somehow be made dynamically since in my local environment I would like to fetch some images from S3 (which is `https`) and some from image-server (which is `http`). Perhaps Virtlet could first assume https and fallback to http on error?

**Comment by jellonek** [comment]
That was my first idea when I started to work on `https` support, but it was rejected quite early.
If we will fall back to insecure connection, we don't have any option to return such information back to user, so this could lead to a tricky, from security perspective, situation.

We can add another option, like `insecure-options` in  https://coreos.com/rkt/docs/latest/commands.html#global-options - and then fall back to `http` when operator will set this option consciously.

WDYT?

**Comment by ivan4th** [comment]
Re `insecure-options`, we don't have any idea about the pod when pulling the image...
Maybe we can add some kind of `insecure-domains` option to Virtlet itself?

**Comment by miha-plesko** [comment]
Is there a reason why we couldn't simply use`virtlet/https://URI` and `virtlet/http://URI`?

**Comment by ivan4th** [comment]
@miha-plesko the part after `:` will get confused with tags. We can just skip `:` of course but that would look... Strange. We may try to invent some kind of syntax for it (e.g. always prepend with `http/` or `https/`) but this needs some thinking so as to make it both usable and non-ugly...

**Comment by jellonek** [comment]
It's not only about tags, it's also prohibited by kubelet and this is why we don't have this from the start.

**Comment by miha-plesko** [comment]
Understood

**Comment by ivan4th** [comment]
BTW I had an idea some time ago of specifying a list of domains to pull VM images from on CRI proxy level. With this in place it's possible to even omit `virtlet/` prefix, as VM images will be recognized by the domain used. So we may actually use this behavior:
1. CRI proxy config includes an optional list of domains for VMs specifying which of them are using http and which are using https
2. If this list is not set, VM image names need to start with `virtlet/http/` or `virtlet/https/`, with plain `virtlet/` prefix being treated as `virtlet/https/`

What do you think folks?

**Comment by ivan4th** [comment]
We're also going to switch to using Helm chart at some point, so this can be easily parameterized (i.e. introduce an option for VM domain list)

**Comment by miha-plesko** [comment]
Sounds interesting, although I'm not sure if cluster admin will be able to predict what domains will users want to have. Also I'm not sure if I want to 'lock' any domain to specific protocol (see cirros example - that domain supports both http and https).

On the other hand I see no big problem with point (2) that you suggest. Perhaps we could make it even more extendable by introducing CRI proxy options like this:
```
virtlet[ssl=true]/URL
```
As far as I've tested, `kubectl` is fine with such format (yaml validation succeeds).

**Comment by jellonek** [comment]
This needs to be passed to virtlet from criproxy, so has to be after `/`. As https is the default, we can add something similar, e.g. `virtlet/[ssl=false]URL`

**Comment by gberginc** [comment]
I was just reviewing the referenced PR and stumbled upon this issue. I would definitely advise against adding such feature. If users are in testing environment or don't care about security, they can change the setting. However, as soon as you allow one VM to be downloaded securely, there should not be some other that is downloaded through an insecure connection as the images can no longer be trusted.

After seeing how a VM can steal the private key from a VM running in parallel just be checking the CPU cache...Brrrr, I'd just close this issue 😄.

**Comment by miha-plesko** [comment]
😨 

I must admit I'm biased to the developer perspective and therefore not care too much about Cirros security. However, I'm closing the issue since I don't feel like sharing my private key with the world!
