### ISSUE TITLE
Container name label not reported to Kubernetes

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#295]
When user invokes `kubectl logs <container>`, Kubernetes searches for logs in file with the following name:
```go
func buildContainerLogsPath(containerName string, restartCount int) string {
	return fmt.Sprintf("%s_%d.log", containerName, restartCount)
}
```
where `containerName` is obtained like this:
```go
containerName := labels["io.kubernetes.container.name"]
```
What bothers me is that filename for Virtlet-powered "containers" appears to always be:
```
_0.log
```
meaning that Kubernetes is missing `io.kubernetes.container.name` label. For cirros example one would actually expect to see log file named as `cirros-vm_0.log`. Is there perhaps some step missing on Virtlet side during container creation that prevents Kubernetes from getting the container name?

Could it perhaps be that container name is intentionally suppressed to emphasize that Virtlet does not work with containers but with Pods only?

### Debugging
I've checked what labels are passed to [`CreateContainer`](https://github.com/Mirantis/virtlet/blob/master/pkg/libvirttools/virtualization.go#L302) function and container name appears to be there since value of `in.Config.Labels[types.KubernetesContainerNameLabel]` is:
```
[map[io.kubernetes.pod.name:cirros-vm io.kubernetes.pod.namespace:default io.kubernetes.pod.uid:22f85076-4216-11e7-b534-02420ac00002 io.kubernetes.container.name:cirros-vm]]
```

**Comment by jellonek** [comment]
As I commented in review: `containerName` in this context is equal to `settings.domainName`, passed as first argument to `v.metadataStore.SetContainer`. This is one of values returned by CRI runtime, and then internally added by kubelet to labels on it's side. At this time kubelet do not knows it and so - can not pass it in its labels.

**Comment by miha-plesko** [comment]
Awesome, I will check (on Monday) if `settings.domainName` is empty string at the time when we're defining libvirt serial filename. If yes, I will use the variable (to produce `_0.log` that Kubernetes expects it), otherwise I will simply hardcode empty string there to produce `_0.log`.

**Comment by jellonek** [comment]
It's defined at the beginning of this func, so it can't be empty ;)
