### ISSUE TITLE
demo.sh is a bit broken after merging `logs`

### ISSUE THREAD

**Issue by jellonek** [Mirantis/virtlet#304]
That's because `logs` branch turned on as default logs, even if comment in https://github.com/Mirantis/virtlet/pull/281/files#diff-cbd52dd8eefa7bebcdd2b305c4bed4afR110 suggests that they should turned on by *uncommenting* below lines.

Easiest fix would be to comment them, but IMO the best solution would be to leave logs turned on, change this comment for enabling/disabling logs, and then switch in demo to use `examples/vmssh.sh` instead of using `virsh console`.

**Comment by miha-plesko** [comment]
I can't decide if it's better to copy the `wait-for-ssh` function from e2e.sh into demo.sh or to update `examples/vmssh.sh` so that it always performs the check first. WDYT?

**Comment by ivan4th** [comment]
I think it's better to have vmssh wait for ssh.

**Comment by ivan4th** [comment]
That's because it can be handy in various situations not involving demo or e2e

**Comment by jellonek** [comment]
+1 for adding this to `vmssh.sh`.

**Comment by miha-plesko** [comment]
I am sorry gentlemen, had to do it somewhat differently. Point is that I couldn't use `examples/vmssh.sh` inside `demo.sh` since AFAIK the `demo.sh` is supposed to be standalone and thus cannot depend on any other script nor file (like ssh keys).
