### ISSUE TITLE
virtlet flexVolume driver doesn't support nocloud 

### ISSUE THREAD

**Issue by vijaykanthm28** [Mirantis/virtlet#318]
I have setup local environment using dind-cluster-v1.6.sh as per your document.
and tried to create VM using cirros-vm.yaml, but it shows me error like 

{kubelet kube-node-1}			Warning		FailedMount	MountVolume.SetUp failed for volume "virtlet/flexvolume_driver/nocloud" (spec.Name: "nocloud") pod "cc2e83f6-4f2b-11e7-b977-02420ac00002" (UID: "cc2e83f6-4f2b-11e7-b977-02420ac00002") with: mount command failed, status: Failure, reason: unknown volume type "nocloud"

but i have searched in your flexvolume driver code but it has nocloud handler.

**Comment by jellonek** [comment]
Your setup is based on [this](https://github.com/Mirantis/virtlet/blob/master/docs/devel/running-local-environment.md#running-local-environment) instruction?
Looks like you missed some point in this list (perhaps you missed second call of `~/dind-cluster-v1.6.sh up`, or second call of `build/cmd.sh start-dind`?). I just entered these instructions in my console, and at the end cirros-vm connected to it using `./examples/vmssh.sh cirros@cirros-vm` without any problem.

**Comment by vijaykanthm28** [comment]
@jellonek thank you 
you are right i have missed the second call of ~/dind-cluster-v1.6.sh up
