### ISSUE TITLE
Document secrets/configmaps as volumes usage

### ISSUE THREAD

**Issue by jellonek** [Mirantis/virtlet#320]
Followup to #319

**Comment by jellonek** [comment]
Kubelet fills volume in quite strange way, creating there real files in dir `..somepid_data_with_subseconds`, which is then linked to `..dir`, to which are created "real" entries as... symlinks.
So file `./something.txt` in source configmap or secret will be in volume dir created in `..somepid_data/something.txt`, which will be visible in root of this volume under name `./something.txt` which links to `..data/something.txt`.

Known limitation of current implementation - if we will have in secret `./sub/dir/file.txt` - it will be not passed into nocloud `write_files`, because it's in subdir `sub`, which in volume dir is symlink to `..data/sub` and current implementation uses golangs `filepath.Walk` - which does not support symlinks to dirs, because this could lead to loops.

**Comment by ivan4th** [comment]
So you mean that only files in the toplevel directory of configmap/secret are written?

**Comment by jellonek** [comment]
Right now, in #319 - yes.

**Comment by jellonek** [comment]
Fixed by #343
