### ISSUE TITLE
Fix delayed undefine of domain after RemoveContainer call was already replied as "success"

### ISSUE THREAD

**Issue by vefimova** [Mirantis/virtlet#341]
Faced to issue during working on https://github.com/Mirantis/virtlet/pull/336: 
For some reason even after 'kubectl get pod' check returns 'NOT FOUND' domain remains defined being in "shut off" state for noticable time.

Ivan recommeded following steps to debug:
> We need to check what's going on here. This may mean that the cleanup mechanism is not doing its job. I'd suggest the following debugging scheme: 1) edit deploy/virtlet-ds-dev.yaml to set VIRTLET_LOGLEVEL=1 2) Add glog.V(0).Infof(...) to critical places like undefining domains etc., you can do this in pkg/libvirttools/libvirt_domain.go etc 3) Switch some critical CRI calls in pkg/manager/manager.go to V(0) logging 4) Reproduce this situation and look at the sequence of CRI calls during this "noticeable time"

**Comment by jellonek** [comment]
Fixed in #361
