### ISSUE TITLE
Fix flexvolume cleanup on "RemoveContainer"

### ISSUE THREAD

**Issue by vefimova** [Mirantis/virtlet#352]
Relates to https://github.com/Mirantis/virtlet/pull/336
Patch adds call of volume cleanup on `StopContainer` as by the time of `RemoveContainer` kubelet's volume manager already cleans up all flexvolume dirs and virtlet flexvolume teardown is never called. So to support uncommon VM lifecycle sequences (as it doesn't excluded explicitly by CRI spec), like `CreateContainer`->`RemoveContainer` we need to be able to clean on `RemoveContainer`.
As possible solutions:
1. store flexvolume data in bolt
2. call cleanup within flexvolume driver

**Comment by jellonek** [comment]
Fixed in #361
