### ISSUE TITLE
Make it possible to run unit tests / check syntax without the build container

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#372]
Some time ago it was difficult to separate Linux-specific code from cross-platform code in Virtlet, but now it's easy to stub out Linux-specific parts. This will help with syntax checkers, code navigation, running unit tests etc. as it will be no longer necessary to do all of this via `build/cmd.sh`.

**Comment by jellonek** [comment]
Already possible and documented in https://github.com/Mirantis/virtlet/blob/master/docs/devel/running-testsuite.md even for MacOS.
