### ISSUE TITLE
Permission denied when executing /vmwrapper

### ISSUE THREAD

**Issue by luckyvega** [Mirantis/virtlet#392]
I have manually deployed a k8s cluster on three ubuntu 16.04 VMs running on vcenter. I would like to try virtlet, so I follow the guide in real-cluster.md to configure one of the node as a virtlet node. Everything goes well until I try to create a VM, I get the following error showed by "kubectl get pod" command:

`rpc error: code = 2 desc = "/run/virtlet.sock": rpc error: code = 2 desc = virError(Code=1, Domain=0, Message='internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOME=/root /vmwrapper -help) unexpected exit status 126: libvirt:  error : **cannot execute binary /vmwrapper: Permission denied**
')`

I guess that's because apparmor is not disabled so I follow the ubuntu official guide to disable apparmor

`sudo systemctl stop apparmor.service`
`sudo update-rc.d -f apparmor remove`

and try to create the VM again, but I get the same error.

I try to list the files in virtlet pod

`sudo kubectl -n kube-system exec virtlet-m5pfz -- ls -l /`

`-rwxr-xr-x   1 root root  4617264 Aug 15 21:54 vmwrapper`

still no hints for the error.

**Comment by ivan4th** [comment]
You need to do `/etc/init.d/apparmor teardown` and then remove apparmor package.

**Comment by jellonek** [comment]
https://support.plesk.com/hc/en-us/articles/213909965-How-to-disable-AppArmor-
As Ivan said - there is additional step.
Btw. dealing with apparmor/selinux can require reboot at the end.

**Comment by luckyvega** [comment]
Thanks for the quick reply, I will try your suggestions.

**Comment by jellonek** [comment]
Also adding `apparmor=0` to kernel command line (in grub configuration) can be useful ;)

**Comment by luckyvega** [comment]
Great, as suggested, after running the following commands and restart my ubuntu virtual machine, I can successfully create a VM via virtlet.

`service apparmor stop`
`service apparmor teardown`
`update-rc.d -f apparmor remove`
`apt-get remove apparmor`

so I close this issue myself?

**Comment by ivan4th** [comment]
Glad it helped :)
