### ISSUE TITLE
Fix duration values in e2e tests

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#403]
E.g. `Eventually` accepts `time.Duration` but we have constructs like `Eventually(..., 60*5, 3)` where delays happen to be expressed in nanosecond. This should look like `Eventually(..., 60 * 5 * time.Second, 3 * time.Second)`. Also we need to check for other places where this may happen.

**Comment by istalker2** [comment]
The docstring for Eventually function says
```
//Both intervals can either be specified as time.Duration, parsable duration strings or as floats/integers.  In the
//last case they are interpreted as seconds.
```
which means that 60*5 is interpreted in seconds since it is integer

Here is where it get parsed: https://github.com/onsi/gomega/blob/master/gomega_dsl.go#L321

**Comment by ivan4th** [comment]
Ok so I got confused by this passage at https://onsi.github.io/gomega/

> These can be passed in as time.Durations, string representations of a time.Duration (e.g. "2s") or float64 values (in which case they are interpreted as seconds).

Apparently this was true in some earlier version of Gomega. Sorry.
