### ISSUE TITLE
Implement streaming server for attach

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#404]
In order to be able to implement support for `kubectl attach`, we need to implement a streaming server. For this we need to convert current `logger` (living in `virtlet-log` container) to bi-directional streaming server that'll also retain its logging functionality. The `logger` binary should be renamed to `streamer` and the container in Virtlet pod should be renamed to `streamer`, too.

The `streamer` (former logger) should now both write pod log files and provide streaming server via http. The following part of kubelet code may be helpful in handling streaming requests: https://github.com/kubernetes/kubernetes/blob/v1.7.5/pkg/kubelet/server/server.go#L596-L664
The streaming server must have proper test coverage.

Virtlet can use the following serial configuration to make the emulator connect to the `streamer`:
```xml
<devices>
  <serial type="unix">
    <source mode="bind" path="/var/lib/virtlet/streamer.sock"/>
    <target port="1"/>
  </serial>
</devices>
```

One problem here is that streamer must somehow determine which VM this is coming from. One possible way is to use [GetPidFromSocket()](pkg/criproxy/pidfromsocket.go) function (it needs to be moved to `pkg/utils` in this case) to retrieve PID of the emulator. When creating the domain, Virtlet can set a number of env vars needed to identify the stream:
- `VIRTLET_POD_NAME`
- `VIRTLET_POD_NAMESPACE`
- `VIRTLET_POD_UID`
- `VIRTLET_CONTAINER_NAME`

The streamer can then examine `/proc/XX/environ` of the emulator process (socket peer) to get the information necessary to provide the stream.

At this stage, the streaming should be enabled only if `VIRTLET_LOG_LOCATION` is set so as not to break `virsh console`.

**Comment by lukaszo** [comment]
Resolved in https://github.com/Mirantis/virtlet/pull/427

**Comment by jellonek** [comment]
Closing it, as it's already resolved in PR mentioned in comment above.
