### ISSUE TITLE
README is missing requirements

### ISSUE THREAD

**Issue by pskrzyns** [Mirantis/virtlet#42]
There should be info that virtlet needs qemu-kvm libvirt-bin etcd installed on the node to work

**Comment by pskrzyns** [comment]
Additionally list of requirements to build would be nice: libguestfs-dev, glib-.2.0-dev autotools ...

**Comment by jellonek** [comment]
For this moment virtlet does not require qemu-kvm or libvirt-bin installed on the node to work - it provides them in containers used to build it (`contrib/docker-compose` what is described in `README.md`).

**Comment by pskrzyns** [comment]
@jellonek like mentioned in other issue docker-compose is mentioned in section ```running local environment``` so unless its the same for production environment, there should be section about node requirements.

**Comment by jellonek** [comment]
Seems legit for me.

**Comment by pskrzyns** [comment]
Additionally basing on @pigmej comment https://github.com/Mirantis/virtlet/issues/40#issuecomment-249907117, there should be info in README that at this moment docker-compose its the only way to run virtlet

**Comment by jellonek** [comment]
Yes, and this is precisely why I reopened this issue (but temporarily - there should be separate issue about usage/build instructions).

**Comment by jellonek** [comment]
Closed by #58
