### ISSUE TITLE
Exited container prevents build/cmd.sh from starting

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#446]
(NOTE: this issue is not of very high priority)

As discussed with @jellonek on Slack, I'm reporting an issue that occurs to me whenever I attempt to build Virtlet after restarting my development machine:

```bash
$ ./build/cmd.sh build
docker: Error response from daemon: Conflict. The container name "/virtlet-build" is already in use by container "64e62beaa1a9395ee6b240042798ab42277ed5b763c7463dc0c7ad3b03ff7b73". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

So it complains that there is already a container with that name. Yes, it's true, but why doesn't it handle it? 😄  :

```bash
$ docker ps -a | grep virtlet_build
64e62beaa1a9        virtlet_build:latest                "/bin/bash -c 'mou..."   5 days ago          Exited (137) 5 days ago                        virtlet-build
```

Even if I want to just purge everything, I'm not allowed to:

```bash
$ ./build/cmd.sh clean
Error response from daemon: unable to remove volume: remove virtlet_src: volume is in use - [64e62beaa1a9395ee6b240042798ab42277ed5b763c7463dc0c7ad3b03ff7b73]
Error response from daemon: unable to remove volume: remove virtlet_pkg: volume is in use - [64e62beaa1a9395ee6b240042798ab42277ed5b763c7463dc0c7ad3b03ff7b73]
Error response from daemon: conflict: unable to remove repository reference "virtlet_build:latest" (must force) - container 64e62beaa1a9 is using its referenced image 689d66e01e9b
```

However, I am able to resolve issue by removing the container manually using Docker CLI:

```
$ docker rm 64e62beaa1a9395ee6b240042798ab42277ed5b763c7463dc0c7ad3b03ff7b73
```

But I guess this should be automated inside `build/cmd.sh`, right?

**Comment by ivan4th** [comment]
@miha-plesko thanks for the bug report! Hopefully #447 will fix it, although you'll still need to do `build/cmd.sh stop`. Later we'll add more sophisticated checks for the build container so it'll happen automagically upon builds etc., there will be proper image version checks and so on.

**Comment by miha-plesko** [comment]
Awesome, I'll test tomorrow morning when I boot my machine.
