### ISSUE TITLE
Network connectivity problem when using CNI bridge in DIND

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#452]
Sometimes ssh'ing into VMs fails, and further inspection reveals that while the VM has booted successfully and DHCP worked as expected, setting up a proper pod IP and a gateway, but the VM has no network connectivity at all, only being able to ping DHCP server IP if you add the necessary address to VM's Ethernet interface.

This is only observed on one developer's machine and, likely, on CircleCI (most e2e flakes are probably manifestations of this problem, too)

**Comment by jellonek** [comment]
Looks like outdated issue. We didn't had such flakes on Circle for looong time.
We can reopen this issue when issue will be back.
