### ISSUE TITLE
can not connect to dockershim.sock

### ISSUE THREAD

**Issue by zhengFrank** [Mirantis/virtlet#459]
criproxy can not connect to dockershim.sock and dockershim can not start with following errors:
Connecting to docker on unix:///var/run/docker.sock
client.go:92] Start docker client with request timeout=2m0s
cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
docker_service.go:208] Docker cri networking managed by kubernetes.io/no-op
docker_service.go:225] Setting cgroupDriver to cgroupfs
dockershim[14093]: error: listen tcp 10.171.216.143:12345: bind: cannot assign requested address
my host ip is 192.168.18.10

**Comment by ivan4th** [comment]
What are the arguments that you pass to kubelet and dockershim?

**Comment by zhengFrank** [comment]
kubelet:
KUBELET_EXTRA_ARGS="--experimental-cri --feature-gates=DynamicKubeletConfig=true --anonymous-auth=true --container-runtime=remote --container-runtime-endpoint=/run/criproxy.sock --image-service-endpoint=/run/criproxy.sock --enable-controller-attach-detach=false"
dockershim:
--api-servers=http://114.29.15.220:8080 --address=114.29.15.206 --hostname-override=node2 --allow-privileged=true --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest --cgroup-driver=cgroupfs --cluster-dns=10.254.0.2 --cluster-domain=cluster.local.

**Comment by ivan4th** [comment]
Do you pass anything besides `$KUBELET_EXTRA_ARGS` to kubelet? E.g. if you have deployed your cluster with kubeadm, you also will have something like `KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin` You need to pass these args to dockershim, too.

**Comment by zhengFrank** [comment]
all args of ps aux|grep kubelet are passed to dockershim; config of kubelet are as follows:
###
## kubernetes kubelet (minion) config
#
## The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS="--address=0.0.0.0"
#
## The port for the info server to serve on
#KUBELET_PORT="--port=10250"
#
## You may leave this blank to use the actual hostname
KUBELET_HOSTNAME="--hostname-override=node2"
#
## location of the api-server
KUBELET_API_SERVER="--api-servers=http://114.29.15.220:8080"
#
## pod infrastructure container
KUBELET_POD_INFRA_CONTAINER="--pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest"
#
## Add your own!
KUBELET_ARGS="--cgroup-driver=cgroupfs --cluster-dns=10.254.0.2 --cluster-domain=cluster.local."
KUBELET_EXTRA_ARGS="--experimental-cri --feature-gates=DynamicKubeletConfig=true --anonymous-auth=true --container-runtime=remote --container-runtime-endpoint=/run/criproxy.sock --image-service-endpoint=/run/criproxy.sock --enable-controller-attach-detach=false

**Comment by ivan4th** [comment]
How did you configure CNI on your nodes?

**Comment by zhengFrank** [comment]
use flannel as network plugin

**Comment by ivan4th** [comment]
What's in `/etc/cni/net.d` ?

**Comment by zhengFrank** [comment]
10-flannel.conf:
{"name":"flannel", 
"type":"flannel"}
add kubelet-network-args to kubelet and dockershim, but the problem remains

**Comment by zhengFrank** [comment]
what's the ip 10.171.216.143:12345 mean? in my opinion dockershim should listen at localhost:12345, if so , how can i change the ip to my host ip ?

**Comment by jellonek** [comment]
Looks like outdated issue. If it's still relevant - please create new one about that in https://github.com/Mirantis/criproxy repo.
