### ISSUE TITLE
no /run/virtlet.sock file

### ISSUE THREAD

**Issue by zhengFrank** [Mirantis/virtlet#466]
kubelet, criproxy and dockershim are running, but criproxy log shows there is no /run/virtlet.sock and kubelet can not connect to criproxy.sock, i did that follows #https://github.com/Mirantis/virtlet/blob/master/deploy/real-cluster.md

thanks

**Comment by lukaszo** [comment]
@zhengFrank sorry for late answer. Is this still a issue for you? If yes please provide virtlet pod logs: `kubectl -n kube-system logs <virtlet-pod> -c virtlet`

**Comment by lukaszo** [comment]
As all issues seems to be connected please continue discussion here https://github.com/Mirantis/virtlet/issues/459
