### ISSUE TITLE
Run CNI plugins in host mount & network namespace

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#471]
There's a two-fold problem with CNI plugin execution in Virtlet:

1. The plugins are executed inside `virtlet` container's mount namespace. This makes the deployments fragile as mounts for the exact set of directories used by particular CNI plugin must be always added to Virtlet daemonset definition.
2. There were problems with CNI plugins accidentally executed in a wrong mount namespace. This has been worked around in #470, but in an ugly way.

A possible solution is for tapfdmanager (part of virtlet binary) to reexecute itself with special env var settings, also employing "CGo constructor" technique from `vmwrapper` to switch namespaces safely. Also, the hack with adding wrappers for CNI plugins must be taken out.

**Comment by jellonek** [comment]
Already done in #561
