### ISSUE TITLE
about inbound license

### ISSUE THREAD

**Issue by lubinsz** [Mirantis/virtlet#487]
What is the agreement for contributions?

It seems that I didn't find the inbound agreement in CONTRIBUTING.md.
In general, the license should be 'Developer Certificate of Origin, version 1.1'. 
My boss want to know the inbound license of this project and the link.

Thanks.

**Comment by istalker2** [comment]
I do not pretend to be a licensing expert, but to my understanding the fact that the project has Apache 2.0 license implies that all contributions must have Apache 2.0 header in all of the files and thus the contribution itself goes with this license and cannot be licensed differently

**Comment by pigmej** [comment]
@lubinsz you're also obligated to sign: https://cla-assistant.io/Mirantis/virtlet

**Comment by lubinsz** [comment]
@istalker2 
@pigmej 
Thanks. This link of https://cla-assistant.io/Mirantis/virtlet is enough for me. Thanks.

**Comment by pigmej** [comment]
@lubinsz then I'm closing the issue :)
