### ISSUE TITLE
etcd container remain spawned after migrated to bolt

### ISSUE THREAD

**Issue by ujnatg** [Mirantis/virtlet#49]
docker ps
[sudo] password for eugen: 
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
39e094d89372        dockercompose_virtlet   "/usr/local/bin/virtl"   9 minutes ago       Up 9 minutes                            dockercompose_virtlet_1
52a22d89ffc8        dockercompose_libvirt   "/start.sh"              15 minutes ago      Up 9 minutes                            dockercompose_libvirt_1
b922672c18cf        quay.io/coreos/etcd     "/usr/local/bin/etcd "   18 hours ago        Up 9 minutes        2379-2380/tcp       dockercompose_etcd_1

**Comment by nhlfr** [comment]
We will most probably remove that - my excuse why I didn't remove that yet - I thought that it may be reused for calico/flannel. But it seems that we will use etcd from k8s for that.
