### ISSUE TITLE
Unable to start an image an a real cluster

### ISSUE THREAD

**Issue by ltouati** [Mirantis/virtlet#493]
Hi Team,

I'm currently investigating the use of virtlet on a real K8S cluster, and I'm facing an issue with the image not being downloaded. I've followed the steps highlighted here https://github.com/Mirantis/virtlet/blob/master/deploy/real-cluster.md

and when launching the cirros vm I have the following errors in the logs

Oct 27 09:14:41 k8s-instance-group-p7t0 kubelet[8301]: I1027 09:14:41.671558    8301 kuberuntime_manager.go:457] Contain
er {Name:cirros-vm Image:virtlet/download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img Command:[] Args:[] Working
Dir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[memory:{i:{value:134217728 scale:0} d:{Dec:<nil>} s: Format:Binary
SI}] Requests:map[memory:{i:{value:134217728 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]} VolumeMounts:[{Name:default-to
ken-ss2l0 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessPr
obe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always S
ecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Oct 27 09:14:41 k8s-instance-group-p7t0 dockerd[3468]: time="2017-10-27T09:14:41.672861446Z" level=error msg="Handler fo
r GET /v1.24/images/virtlet/download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img:latest/json returned error: No 
such image: virtlet/download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img:latest"
Oct 27 09:14:41 k8s-instance-group-p7t0 kubelet[8301]: E1027 09:14:41.673438    8301 kuberuntime_manager.go:718] contain
er start failed: ImagePullBackOff: Back-off pulling image "virtlet/download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-d
isk.img"
Oct 27 09:14:41 k8s-instance-group-p7t0 kubelet[8301]: E1027 09:14:41.673473    8301 pod_workers.go:182] Error syncing p
od d40a4610-baf0-11e7-a684-42010a840003 ("cirros-vm_default(d40a4610-baf0-11e7-a684-42010a840003)"), skipping: failed to
 "StartContainer" for "cirros-vm" with ImagePullBackOff: "Back-off pulling image \"virtlet/download.cirros-cloud.net/0.3
.5/cirros-0.3.5-x86_64-disk.img\""
Oct 27 09:14:42 k8s-instance-group-p7t0 kubelet[8301]: I1027 09:14:42.267387    8301 server.go:244] Checking API server 
for new Kubelet configuration.

**Comment by jellonek** [comment]
Can you share on which version of k8s you are trying that?
Looks like our `criproxy` was not configured properly and request for image is passed directly to docker runtime. Can you paste there `kubelet` configuration? Please also take a look on `criproxy` logs which should be available under the `journalctl`.

**Comment by ltouati** [comment]
Hi

Right the criproxy was not configured properly. I did not remove the 20-virtlet.conf file.

Just removed it and restarted and it works now

Thx and sorry for this
