### ISSUE TITLE
Routing issue with Ubuntu VM and Flannel

### ISSUE THREAD

**Issue by ltouati** [Mirantis/virtlet#495]
Hi Team,

When creating a VM based on ubuntu the default route is not created making the VM unable to connect to the outside world.

When deploying the cirros example however the route is properly created

**Comment by jellonek** [comment]
Cirros does not support network configuration in cloud init, instead using dhcp based fallback, which looks like is working ok, while Ubuntu uses cloud init based netconf, where we probably have a source of this issue.
Will try to look on that deeper in near future.

**Comment by ltouati** [comment]
Just added a small init script to correct this
```bash
GATEWAY=`netstat -nr |grep .0.0 | head -1 | tr -s " " | cut -f 2 -d " "`
route add -net 0.0.0.0/0 gw $GATEWAY
```
Hope this helps

**Comment by jellonek** [comment]
Can you post there configuration of CNI flannel plugin?
Also please in vm mount somewhere `/dev/sr0` and paste there content of `network-config` from it.
I'm trying to replicate this issue, but i have default route in ubuntu vm (so that looks like different configuration issue).

**Comment by jellonek** [comment]
As #509 is already merged and it fixed also these routes - can you confirm if that resolved your issue?

**Comment by ltouati** [comment]
Yes it did

Thx
