### ISSUE TITLE
Virtlet won't deploy

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#512]
I'm excited to run Virtlet on DIND cluster with Kubernetes 1.8, but the demo.sh script seems to get stuck for some reason. The command that I ran was as simple as `./deploy/demo.sh` and everything seemed to be fine until waiting for Virtlet DaemonSet got stuck. Below please find the full out console output:

[demo-output.txt](https://github.com/Mirantis/virtlet/files/1500916/demo-output.txt)

I kindly ask for help!

**Comment by ivan4th** [comment]
Please try `VIRTLET_DEMO_BRANCH=master ./demo.sh`
We're going to make a new release soon that will fix the deployment issue that appeared after CRI proxy separation, but for now you can just use Virtlet image for master branch as shown above.

**Comment by miha-plesko** [comment]
Aha, it seems like the mirantis/virtlet container on the DockerHub is either corrupt or obsolete. After manually building it and then running `INJECT_LOCAL_IMAGE=yes BASE_LOCATION=$VIRTLET_DIR VIRTLET_DEMO_BRANCH=master ./deploy/demo.sh` the cluster deployment succeeds.

**Comment by pigmej** [comment]
@miha-plesko the image was ok, but demo uses release not master branch, you can change that in the way as @ivan4th wrote :)

Ps. release is incoming
