### ISSUE TITLE
Cannot access Kubernetes REST API from within a Pod

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#513]
So I've deployed DIND cluster by means of demo.sh script (using the default `CNI_PLUGIN=bridge`). Then I create a Docker container in there and I need to access the k8s REST API (to list Pods) from within that container. The official k8s [documentation](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod) claims that it should be as easy as:

*Kubernetes apiserver is accessible via a Service named kubernetes in the default namespace. Therefore, Pods can use the `kubernetes.default` hostname to query the API server.*

But for some reason this does not work on DIND cluster and I'm not sure why. Is there perhaps some extra installation step that I'd need to perform? I've tested both with `bridge` and `calico` networking.

```
# curl https://kubernetes.default/api/v1/namespaces/default/pods                                                
curl: (35) SSL connect error
```

I do realize that this is not directly a Virtlet-related question, but I kindly ask for a suggestion anyway.

**Comment by jellonek** [comment]
I don't have yet quick solution for this, but imo `kubernetes` service needs to be update.
Now it points to:
```
kubectl describe service kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.96.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.192.0.2:6443
Session Affinity:  ClientIP
Events:            <none>
```
but it's accessible from host on:
```
cat .kube/config
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://10.192.0.2:8080
  name: dind
...
```
so probably it need so be updated from https to http and from port 6443 to port 8080.
idk if it's enough help to start digging deeper.

**Comment by miha-plesko** [comment]
Unfortunately this specific service seems to behave different than others (it has `Selector: <none>`) so I have no idea how Endpoint is then matched. Because if I update the Service name from "https" to "http" and fix the ports, then no Pod is matched anymore for some reason.

Do you perhaps know where this service gets deployed? I couldn't find it on https://github.com/Mirantis/kubeadm-dind-cluster/.

**Comment by jellonek** [comment]
That should also be working with 443/6443 as apisever is listening for that on kube-master. Can not look onto more right now. Will try to look on that later.

**Comment by ivan4th** [comment]
@miha-plesko when accessing apiserver from a pod, you must utilize service account data that's mounted into it (in case of Virtlet, it's copied using cloud-init mechanism). So for example this will work if service account is granted enough permissions:
```
(cd /var/run/secrets/kubernetes.io/serviceaccount/..data/ && curl --cacert ca.crt -H "Authorization: Bearer $(cat token)" https://kubernetes.default/api/v1/namespaces/default/pods)
```
Very quick/dirty/unrecommended way to get RBAC out of the way if you want to test this:
```
kubectl create clusterrolebinding permissive-binding  --clusterrole=cluster-admin  --user=admin --user=kubelet --group=system:serviceaccounts
```
(for more advanced settings, see k8s RBAC docs)

**Comment by lukaszo** [comment]
Issue is not virtlet related
