### ISSUE TITLE
Networking issues when bursting

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#519]
I have an application that consists of multiple VMs (unikernels actually, but it's the same). Everything works well UNLESS if I try to provision all the 7 unikernels at the same time using the command:

```bash
$ kubectl create -f all-unikernels.yaml
```

If I do this, then some VMs get the IP address and some don't. But if I do it like this:

```bash
$ kubectl create -f 1st-unikernel.yaml
# wait for it to provision
$ kubectl create -f 2nd-unikernel.yaml
# wait for it to provision
$ kubectl create -f 3rd-unikernel.yaml
# wait for it to provision
$ kubectl create -f 4th-unikernel.yaml
# wait for it to provision
$ kubectl create -f 5th-unikernel.yaml
# wait for it to provision
$ kubectl create -f 6th-unikernel.yaml
# wait for it to provision
$ kubectl create -f 7th-unikernel.yaml
# wait for it to provision
```

Then it works normally. As far as I've tested it still works if I provision 2 unikernels at the same time, but with 3 it sometimes work and sometimes not. I've also tested with Deployment: when I set 3 replicas, it sometimes work and sometimes not. With 4 replicas it never works.

Now, it could be a bug in our unikernels that they crash in case "networking arrives late" or something, but do you guys know what is happening here? I need to know what happens in Virtlet so that I can then know what to look at in our unikernel.

/cc @justinc1 @gberginc - does it ring any bell to you, perhaps? Only `2017-12-01T09:00:29Z OSv v0.24-462-gd9a8771` line is prineted when this occurs and nothing afterwards. Just nothing.

**Comment by miha-plesko** [comment]
@jellonek  @ivan4th I'm sorry to push it, but I'd kindly ask for a quick blind guess. I'm pretty sure it worked well some time ago (maybe few months ago), but now this issue appeared (I'm using `CNI_PLUGIN=bridge`), and I only need to know if the bug is fixable until the end of 2017. For the sake of writing some report. Thanks!

**Comment by lukaszo** [comment]
Is this one node setup?

**Comment by miha-plesko** [comment]
Yes, it's a DIND cluster that I setup with `demo.sh` script:

```
CNI_PLUGIN=bridge INJECT_LOCAL_IMAGE=yes BASE_LOCATION=$VIRTLET_DIR VIRTLET_DEMO_BRANCH=master ./deploy/demo.sh
```

My Virtlet container image was last compiled two weeks ago or so.

**Comment by miha-plesko** [comment]
Aha, so it's a two-node setup, but only one node has Virtlet installed and my Deployments contain the `nodeAffinity` stanza to get deployed on node-1 everytime.

**Comment by ivan4th** [comment]
>My Virtlet container image was last compiled two weeks ago or so.

Would you please try to use current virtlet master? Because there's possibility there was some network breakage 2 weeks ago.

**Comment by miha-plesko** [comment]
Unfortunately I couldn't play more with this today, I just deployed them one by one to continue the demo. Will try the above suggestions when I return from Kubecon ;)

**Comment by jellonek** [comment]
Most important question is one asked by Ivan - on which commit was based virtlet image used in tests.
If it will be not resolved till my return from kubecon - will try to look on that, but interesting is what you have in virtlet logs (for that i would disable in code logging all ListSomething requests), especially if there were during dhcp requests (close to `StartContainer` logs) matching cni results dumped during calls to `RunPodSandbox`. Because you are configuring networking in unikernels using plain dhcp, without a help of NoCloud network configuration, right?

**Comment by lukaszo** [comment]
@miha-plesko is this still happening on the current Virtlet?

**Comment by miha-plesko** [comment]
Closing the issue since I have no Virtlet deployment at hand anymore, unfortunately.
