### ISSUE TITLE
Performance/Cost analysis to migrate workload to Virtlet

### ISSUE THREAD

**Issue by kshafiee** [Mirantis/virtlet#524]
I was wondering if the Virtlet team may have done any performance/cost analysis in terms of whether, how much cost reduction can be expected from migrating workload from VMs into VM Pods.

For instance, if an enterprise is now running their Windows app. on Windows VMs, should they expect any reduction in expenses if they migrate their workload to VM pods using Virtlet?

@jellonek @pigmej

**Comment by pigmej** [comment]
Hey @kshafiee we didn't do such analysis. There are many questions in that area. What is the current virtualization platform, what is it's setup etc. Virtlet is quite lightweight, k8s also. There is nothing big that can bump the cost. And you will have unified platform for containers and vms, which is huge win.

**Comment by lukaszo** [comment]
There seems to be nothing more to add here so closing. @kshafiee if have more questions please feel free to reopen it.
