### ISSUE TITLE
readme file issues

### ISSUE THREAD

**Issue by YevhenD** [Mirantis/virtlet#54]
- wrong command for creating virtual environment  "mkvirtualenv docker-compose" probably should be "virtualenv docker-compose"

- virtual env activate command omitted

- adding current user into docker group not mentioned (groupadd docker)

- apparmor/selinux disabling notes not mentioned

- host process of libvirt disabling notes not mentioned

- recomended kubernetes version not mentioned for kubelet

**Comment by jellonek** [comment]
`mkvirtualenv` is the right command, if you are using http://virtualenvwrapper.readthedocs.io/
Also this does not require env activation (but still could be activated using `workon name_of_env`.

So mention about apparmor/selinux, virtualenvwrapper, disabling host libvirt and other dependencies for sure should be mentioned in `README.md`.

**Comment by pigmej** [comment]
@jellonek we can suggest normal virtualenv + activation. No need to install yet another tool if someone is not using it.

**Comment by YevhenD** [comment]
@jellonek thanks for your detailed comment. you are right.

**Comment by jellonek** [comment]
Closed in #58
