### ISSUE TITLE
Support for image types other than qcow2, such as iso, ami, ovf, vdi

### ISSUE THREAD

**Issue by kshafiee** [Mirantis/virtlet#564]

**Comment by jellonek** [comment]
There is a missing info about that in docs, but .iso or other raw data types should work out of the box (image is just passed by libvirt to qemu - anything what qemu can handle - should work without any additional code).

Other mentioned image types will require use of `qemu-img` or even something more (ami is afair not recognizable by qemu-img). That could lead to additional time needed by our machinery during download phase, but should be quite easy to code.

Anyway - any patches welcomed ;)

**Comment by jellonek** [comment]
Ups. That (.iso, .raw) was working up to last changes in image store usage, so above comment is partially incorrect.
