### ISSUE TITLE
Error: InvalidImageName

### ISSUE THREAD

**Issue by tidowu** [Mirantis/virtlet#711]
I have been trying to figure out a way to point to a local image. For example I have an image file in my root directory. How I point to it?

Current Setup:
 I set it up as `**image: /home/olatoyei/kube-worker-1-disk1.img**`

When I create pod I get `**Error: InvalidImageName**`

Any help will be appreciated

**Comment by jellonek** [comment]
There is no support for local images (it's not clear to which machine this local image path should be correct).
You can always serve this file using `python2 -m SimpleHTTPServer` then point image location in pod to this file on this server.
