### ISSUE TITLE
How does it compare to Kata containers?

### ISSUE THREAD

**Issue by tamalsaha** [Mirantis/virtlet#717]
I was reading  https://www.mirantis.com/blog/kubevirt-vs-virtlet-comparison-better/ post . I wanted to ask this question.

**Comment by ivan4th** [comment]
Hi. Kata Containers is intended to run container images. Virtlet can run arbitrary QCOW2 virtual machine images that are compatible with KVM, at the same time making them fit into the Kubernetes cluster as seamlessly as possible.

**Comment by jellonek** [comment]
In simpler words - with kata containers you are starting in kubernetes environment pods based on normal docker images, but instead with docker which uses host kernel - using qemu with a separate kernel in VM. That gives you a VM level of security for docker image based containers.

Virtlet on the other hand provides you a way of starting in parallel of other docker based pods also "normal" VMs (with images in qemu qcow2 format, as in openstack) in kubernetes environment which will have the same (we are trying to do that as possible) user interfaces as other docker based pods. That allows you to have in same kubernetes cluster software running on linux and on other systems (bsd, unikernels, windows). This also allows you to use a set of linux kernel modules (or even different version of linux kernel) on bare metal host different from used in VM, possibly required by application.

**Comment by tamalsaha** [comment]
Thanks folks for the clear explanation :) . I understand the diff. Cool project!
