### ISSUE TITLE
Question: VirtletCloudInitUserDataSource from configmap has no effect

### ISSUE THREAD

**Issue by ramukima** [Mirantis/virtlet#748]
With the following annotations, should I expect the user-data content to be written from the configmap test ?

```
VirtletCloudInitUserDataOverwrite: "true"
VirtletCloudInitImageType: configdrive
VirtletCloudInitUserDataSource: configmap/test
```

My intent is to just have the content of my config map written into the user-data file and nothing else.

**Comment by jellonek** [comment]
If `VirtletCloudInitUserDataOverwrite` is set to `true`, generated image will have only data from `VirtletCloudInitUserData` which in fact is disabling fetching data from this configmap. It's documented in https://github.com/Mirantis/virtlet/blob/master/docs/cloud-init-data-generation.md#propagating-user-data-from-kubernetes-objects

If you wan't to use data from configmap - simply do not set `VirtletCloudInitUserDataOverwrite` to true, so in result generated data will have a merged value from annotations (which you can leave empty) + from data sources (configmap of secret).

**Comment by jellonek** [comment]
What I described above - would have a place only if `VirtletCloudInitUserData` had any value set, but it's empty (or omitted?) in initial example.
With data from this example - actually that should work as you described, so I'll look on to that deeper tomorrow.

**Comment by jellonek** [comment]
`VirtletCloudInitUserDataOverwrite: "true"` disables merging of key values procedure, it does not mean that final `user_data` will have shape from only one data source, also excluding other things like volumes (and pod will have always at last single volume - default secret). It's used only when user data has to be generated basing on `VirtletCloudInitUserData` annotation.

There would be a possibility to implement a different behavior, e.g. where whole content of `user_data` file could be constructed from config map (which then would be dumped as yaml) or even to take a value from a selected config map entry and use it as plain text (or encoded somehow, e.g. with base64).
