### ISSUE TITLE
Switch to containerd

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#766]
Right now there are problems with dockershim not returning proper container stats when run behind CRI Proxy. We need to switch from dockershim to containerd to mitigate this problem. Later, we may also get rid of CRI Proxy entirely by using containerd plugin mechanisms.

**Comment by chengyli** [comment]
@ivan4th 
Are you working on using cri-containered instead of cri proxy? 
Also how bout using cri-o?

**Comment by intlabs** [comment]
I'd also be very interested in CRI-O support.
