### ISSUE TITLE
storage: Ephemeral volumes are not removed after domain is destroyed.

### ISSUE THREAD

**Issue by jellonek** [Mirantis/virtlet#78]
We are creating new volumes during `CreateContainer`/`processVolumes` using `volumeStorage.CreateVol` (btw. imo this should be renamed into `CreateVolume`) but we are not removing them at any point later.

Because of lacking this removal right now we have situation like described by @nhlfr:
```
virtlet_1  | libvirt: Storage Driver error : storage volume 'cirros__var_run_secrets_kubernetes.io_serviceaccount' exists already
virtlet_1  | E1010 15:07:49.279520       1 manager.go:180] Error when creating container cirros: &errors.errorString{s:"storage volume 'cirros__var_run_secrets_kubernetes.io_serviceaccount' exists already"}
```

Good place for this seems to be `RemoveContainer` just after call to `C.destroyAndUndefineDomain`.

**Comment by vefimova** [comment]
It's a dup of https://github.com/Mirantis/virtlet/issues/38
