### ISSUE TITLE
Tracking issue for untested PRs

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#791]
This issue lists the PRs (merged and to-be-merged) that need tests.

#728  support to set cpu model with more detail
#739 Implement directory volume for virtlet with 9pfs
#770  Add an option to store whole user-data in secret/configmap entry
#775 Tuning rootfs using config map as files source (e2e: #798 but also needs unit test)
#782 Cpusets support (to be merged)
#831 Set cpuset for emulator during UpdateContainerResources

**Comment by ivan4th** [comment]
bump

**Comment by jellonek** [comment]
#775 covered in #861 
#782 and #831 covered in #853
