### ISSUE TITLE
netns issue

### ISSUE THREAD

**Issue by volume-ji** [Mirantis/virtlet#808]
**There are some below steps to lead to this issue.**
1. there is no any CNI plugin in kubernetes
2. I create a vmpod by using "kubectl create -f xx.yaml". the vmpod is containercreating forever because of no CNI.
3. I create a podid netns using "ip netns add <podid>"
4. I can see the error from virtlet logs. "ip netns add <podid>" failed with output: Cannot create namespace file "/var/run/netns/<podid>": File exists""
5. I recover CNI plugin. either weave or flannel.
6. the vmpod is not running forever.

**Comment by jellonek** [comment]
That's because Virtlet supports only CNI based configuration. Also manual adding netns for pod misleads Virtlet leading to another erroneous situation.

If there is no CNI plugin (p. 1), how you are recovering weave or flannel (p. 5)?

**Comment by volume-ji** [comment]
at the beginning, I do not create CNI plugin, and manually create netns using "ip netns add <podid>", then I can get the error "netns File exists". at the last, I create CNI plugin using "kubectl apply -f weave-net.yaml", the vmpod do not become "running".
I know this situation is very abnormal. 
I looked at the code flow in RunPodSandbox function by invoking TapFDSource.GetFDs(137 line, tapFDSource file),  if netns create failure, directly return error. but if the error is "the netns have been exist", the netns will not be deleted. then the error is again and again. Of course I know, it is not abnormal to create netns manually.
