### ISSUE TITLE
netns Device or resource busy

### ISSUE THREAD

**Issue by volume-ji** [Mirantis/virtlet#809]
k8s: v1.10.1
CNI: knitter

I got a error "Device or resource busy" when reboot the node that scheduled one vmpod, my CNI plugin is bad beacuse that there is nothing daemon except knitter-plugin.

```
[root@paas-controller-172-21-0-2:/home/ubuntu]$ kubectl get po
NAME           READY     STATUS              RESTARTS   AGE
windows-pict   0/1       ContainerCreating   0          1h
[root@paas-controller-172-21-0-2:/home/ubuntu]$ ip netns
RTNETLINK answers: Invalid argument
qrouter-7dac828a-7572-4552-83c5-9e1c8db65d65
qrouter-2fdb5e86-e8ec-48b2-8163-dcd675859944
RTNETLINK answers: Invalid argument
e0841e48-f15e-11e8-8723-0c1262f5431b
[root@paas-controller-172-21-0-2:/home/ubuntu]$ ip netns delete e0841e48-f15e-11e8-8723-0c1262f5431b
RTNETLINK answers: Invalid argument
Cannot remove namespace file "/var/run/netns/e0841e48-f15e-11e8-8723-0c1262f5431b": Device or resource busy
[root@paas-controller-172-21-0-2:/home/ubuntu]$ kubectl get po -n kube-system
NAME             READY     STATUS    RESTARTS   AGE
iag-172.21.0.2   1/1       Running   113        42d
virtlet-7fwq6    3/3       Running   18         1h
[root@paas-controller-172-21-0-2:/home/ubuntu]$ kubectl logs -n kube-system -c virtlet virtlet-7fwq6 | less
[root@paas-controller-172-21-0-2:/home/ubuntu]$ kubectl get po -o yaml | grep uid
    uid: e0841e48-f15e-11e8-8723-0c1262f5431b
[root@paas-controller-172-21-0-2:/home/ubuntu]$ kubectl logs -n kube-system -c virtlet virtlet-7fwq6
I1126 09:40:07.626956    9838 listener.go:66] UnixSocket Listener started
I1126 09:40:07.636107    9838 manager.go:156] Starting server on socket /run/virtlet.sock
2018/11/26 09:40:07 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write unix /run/virtlet.sock->@: write: broken pipe"
nsfix reexec: pid 10010: entering the namespaces of target pid 1
"Log":"2018-11-26 17:40:07.858136       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=3096733085240003  InstanceID=10025        [ObjectType=null,ObjectID=null]    KnitterAgent post error! -Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused   [main.go] [145]"
"Log":"2018-11-26 17:40:07.858341       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=3096733085240003  InstanceID=10025        [ObjectType=null,ObjectID=null]    SendPostWithRetry(reqJSON:[{"ContainerID":"e0841e48-f15e-11e8-8723-0c1262f5431b","Netns":"/var/run/netns/e0841e48-f15e-11e8-8723-0c1262f5431b","IfName":"virtlet-eth0","Args":"IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=windows-pict;K8S_POD_INFRA_CONTAINER_ID=e0841e48-f15e-11e8-8723-0c1262f5431b;K8S_ANNOT={\"cni\": \"calico\"}","Path":"/opt/cni/bin","StdinData":"eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoia25pdHRlciIsInR5cGUiOiJrbml0dGVyIn0="}], url:[http://127.0.0.1:1077/v1/pod?operation=attach]) err, error is [Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused] [main.go]       [135]"
2018/11/26 09:40:17 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2018/11/26 09:40:27 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2018/11/26 09:40:37 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
"Log":"2018-11-26 17:40:37.857931       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=3096733085240003  InstanceID=10025        [ObjectType=null,ObjectID=null]    [Attach ports to POD error: Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused]        [main.go]  [69]"
E1126 17:40:37.866625   10010 client.go:169] AddSandboxToNetwork: PodID "e0841e48-f15e-11e8-8723-0c1262f5431b", PodName "windows-pict", PodNs "default": error: Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused
E1126 09:40:37.876813    9838 ns.go:48] "ip netns del e0841e48-f15e-11e8-8723-0c1262f5431b" failed with output: Cannot remove namespace file "/var/run/netns/e0841e48-f15e-11e8-8723-0c1262f5431b": Device or resource busy
E1126 09:40:37.876845    9838 tapfdsource.go:157] Error removing netns after failed network setup: exit status 1
E1126 09:40:37.877175    9838 runtime.go:159] Error removing pod windows-pict (e0841e48-f15e-11e8-8723-0c1262f5431b) from CNI network: server returned error: error releasing fd: bad fd key: "e0841e48-f15e-11e8-8723-0c1262f5431b"
```

**Comment by volume-ji** [comment]
/kind issue
I will appreciate for any reply, thanks

**Comment by jellonek** [comment]
Which version of virtlet you are using?
This issue should be resolved by #790, so that should be fixed on latest v1.4.2 release.

**Comment by volume-ji** [comment]
···
[root@paas-controller-172-21-0-2:/home/ubuntu]$ kubectl logs -n kube-system -c virtlet virtlet-b5lrw
Waiting for libvirt...
Waiting for libvirt...
Waiting for libvirt...
I1127 03:46:03.182135   27849 listener.go:66] UnixSocket Listener started
W1127 03:46:03.223643   27849 manager.go:153] errors encountered during recover / GC:
* error recovering VM network namespaces: can't verify container status for container "b66ec2a2-f108-5ac0-4497-f9454a2848e7" in pod "86c86770-f1f6-11e8-8913-0c1262f5431b": domain not found
* error performing libvirt GC: cannot list containers for pod 86c86770-f1f6-11e8-8913-0c1262f5431b: pod sandbox "86c86770-f1f6-11e8-8913-0c1262f5431b" does not exist
I1127 03:46:03.223669   27849 manager.go:156] Starting server on socket /run/virtlet.sock
2018/11/27 03:46:03 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write unix /run/virtlet.sock->@: write: broken pipe"
nsfix reexec: pid 28368: entering the namespaces of target pid 1
"Log":"2018-11-27 11:46:03.618981       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=5630218945751778  InstanceID=28388        [ObjectType=null,ObjectID=null]    KnitterAgent post error! -Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused   [main.go] [145]"
"Log":"2018-11-27 11:46:03.619129       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=5630218945751778  InstanceID=28388        [ObjectType=null,ObjectID=null]    SendPostWithRetry(reqJSON:[{"ContainerID":"86c86770-f1f6-11e8-8913-0c1262f5431b","Netns":"/var/run/netns/86c86770-f1f6-11e8-8913-0c1262f5431b","IfName":"virtlet-eth0","Args":"IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=windows-pict;K8S_POD_INFRA_CONTAINER_ID=86c86770-f1f6-11e8-8913-0c1262f5431b;K8S_ANNOT={\"cni\": \"calico\"}","Path":"/opt/cni/bin","StdinData":"eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoia25pdHRlciIsInR5cGUiOiJrbml0dGVyIn0="}], url:[http://127.0.0.1:1077/v1/pod?operation=attach]) err, error is [Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused] [main.go]       [135]"
2018/11/27 03:46:29 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
"Log":"2018-11-27 11:46:33.618683       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=5630218945751778  InstanceID=28388        [ObjectType=null,ObjectID=null]    [Attach ports to POD error: Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused]        [main.go]  [69]"
E1127 11:46:33.628711   28368 client.go:169] AddSandboxToNetwork: PodID "86c86770-f1f6-11e8-8913-0c1262f5431b", PodName "windows-pict", PodNs "default": error: Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused
E1127 03:46:33.638327   27849 runtime.go:159] Error removing pod windows-pict (86c86770-f1f6-11e8-8913-0c1262f5431b) from CNI network: server returned error: error releasing fd: bad fd key: "86c86770-f1f6-11e8-8913-0c1262f5431b"
2018/11/27 03:46:39 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
nsfix reexec: pid 1022: entering the namespaces of target pid 1
"Log":"2018-11-27 11:46:45.853937       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=4575937185960230  InstanceID=1035 [ObjectType=null,ObjectID=null]    KnitterAgent post error! -Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused   [main.go]       [145]"
"Log":"2018-11-27 11:46:45.854126       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=4575937185960230  InstanceID=1035 [ObjectType=null,ObjectID=null]    SendPostWithRetry(reqJSON:[{"ContainerID":"86c86770-f1f6-11e8-8913-0c1262f5431b","Netns":"/var/run/netns/86c86770-f1f6-11e8-8913-0c1262f5431b","IfName":"virtlet-eth0","Args":"IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=windows-pict;K8S_POD_INFRA_CONTAINER_ID=86c86770-f1f6-11e8-8913-0c1262f5431b;K8S_ANNOT={\"cni\": \"calico\"}","Path":"/opt/cni/bin","StdinData":"eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoia25pdHRlciIsInR5cGUiOiJrbml0dGVyIn0="}], url:[http://127.0.0.1:1077/v1/pod?operation=attach]) err, error is [Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused] [main.go]       [135]"
2018/11/27 03:46:49 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2018/11/27 03:46:59 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2018/11/27 03:47:09 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
"Log":"2018-11-27 11:47:15.853346       ERROR   paas-controller-172-21-0-2      knitter.knitter-plugin  TransactionID=4575937185960230  InstanceID=1035 [ObjectType=null,ObjectID=null]    [Attach ports to POD error: Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused]        [main.go] [69]"
E1127 11:47:15.860393    1022 client.go:169] AddSandboxToNetwork: PodID "86c86770-f1f6-11e8-8913-0c1262f5431b", PodName "windows-pict", PodNs "default": error: Post http://127.0.0.1:1077/v1/pod?operation=attach: dial tcp 127.0.0.1:1077: getsockopt: connection refused
E1127 03:47:15.874995   27849 ns.go:48] "ip netns del 86c86770-f1f6-11e8-8913-0c1262f5431b" failed with output: Cannot remove namespace file "/var/run/netns/86c86770-f1f6-11e8-8913-0c1262f5431b": Device or resource busy
E1127 03:47:15.875013   27849 tapfdsource.go:158] Error removing netns after failed network setup: exit status 1
E1127 03:47:15.875237   27849 runtime.go:159] Error removing pod windows-pict (86c86770-f1f6-11e8-8913-0c1262f5431b) from CNI network: server returned error: error releasing fd: bad fd key: "86c86770-f1f6-11e8-8913-0c1262f5431b"
2018/11/27 03:47:19 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2018/11/27 03:47:29 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
E1127 03:47:30.814756   27849 ns.go:48] "ip netns add 86c86770-f1f6-11e8-8913-0c1262f5431b" failed with output: RTNETLINK answers: Invalid argument
Cannot create namespace file "/var/run/netns/86c86770-f1f6-11e8-8913-0c1262f5431b": File exists
E1127 03:47:30.816136   27849 ns.go:48] "ip netns del 86c86770-f1f6-11e8-8913-0c1262f5431b" failed with output: RTNETLINK answers: Invalid argument
Cannot remove namespace file "/var/run/netns/86c86770-f1f6-11e8-8913-0c1262f5431b": Device or resource busy
E1127 03:47:30.816390   27849 runtime.go:159] Error removing pod windows-pict (86c86770-f1f6-11e8-8913-0c1262f5431b) from CNI network: server returned error: error releasing fd: bad fd key: "86c86770-f1f6-11e8-8913-0c1262f5431b"
···
1. invoke virtletManager.recoverAndGC() failure，I get a error "errors encountered during recover / GC..."
2. invoke RunPodSandbox, the first invoking CNI failure, but it can normally create and delete netns.
3. invoke RunPodSandbox, the second invoking CNI failure, it can normally create netns but remove netns failure.

**Comment by volume-ji** [comment]
I suspect that there are something wrong in my CNI plugin, but the CNI plugin do not use the netns ,it only post the body to the CNI agent which do not start and have a error "connect refused". 

In this situation, there are some errors using "ip netns",  the netns file mode is "----------", and the netns file "/var/run/netns/podid" can not delete.
```
qrouter-7dac828a-7572-4552-83c5-9e1c8db65d65
qrouter-2fdb5e86-e8ec-48b2-8163-dcd675859944
RTNETLINK answers: Invalid argument
c7f7fac9-f20d-11e8-955e-0c1262f5431b

[root@paas-controller-172-21-0-2:/home/ubuntu]$ ls -la /var/run/netns/c7f7fac9-f20d-11e8-955e-0c1262f5431b
---------- 1 root root 0 Nov 27 14:33 /var/run/netns/c7f7fac9-f20d-11e8-955e-0c1262f5431b
[root@paas-controller-172-21-0-2:/home/ubuntu]$ rm -rf /var/run/netns/c7f7fac9-f20d-11e8-955e-0c1262f5431b
rm: cannot remove ‘/var/run/netns/c7f7fac9-f20d-11e8-955e-0c1262f5431b’: Device or resource busy

```

**Comment by volume-ji** [comment]
I do not understand why the CNI plugin carrying on netns post failure will lead to the netns deleting failure: "device or resource busy", but I can reslove this issue by modifying the CNI plugin code. CNI plugin probe whether the server is ready before send the post request. 
close the issue.
