### ISSUE TITLE
GPL license about "pkg/diskimage/guestfs/guestfs.go"

### ISSUE THREAD

**Issue by volume-ji** [Mirantis/virtlet#822]
There is a GPL license in code "pkg/diskimage/guestfs/guestfs.go" about formating disk image, which add because of PR #18 and mentions LGPL license. does it effect whole apache 2.0 license?  will GPL license infection all program to GPL?

**Comment by jellonek** [comment]
We are linking to non modified file with this licence so afaik it's ok.

**Comment by jellonek** [comment]
Actually according to https://www.apache.org/legal/resolved.html#category-x there could be an issue with it. I'll try to escalate the issue to our lawyers.

**Comment by volume-ji** [comment]
OK, get it
