### ISSUE TITLE
Documentation Links Broken

### ISSUE THREAD

**Issue by rcsavage** [Mirantis/virtlet#859]
Come On Guys Your documentation links are broken and are all out of whack on the master branch

This is referenced on your master branch README.md: ( Running local environment )
https://github.com/Mirantis/virtlet/blob/master/docs/devel/running-local-environment.md

Doesn't work 404

Deploy Using DaemonSets -> https://github.com/rcsavage/virtlet/blob/master/deploy/README.md

Also does not work - 404

Separate Document->https://github.com/rcsavage/virtlet/blob/master/deploy/real-cluster.md

Does not work - 404

**Comment by ivan4th** [comment]
Oops, sorry, failed to update README.md after setting up new mkdocs-based docs. #860 will fix this
