### ISSUE TITLE
Support vhost-net

### ISSUE THREAD

**Issue by keyingliu** [Mirantis/virtlet#868]
The network parameters are populated in vmwrapper, after a VM is launched, the network parameters look like:
```
-netdev tap,id=tap0,fd=5 -device
```

But as we know for device `virtio-net-pci`, the vhost-net is supported, and shloud be able to improve network IO performance, can we add it in virtlet too? like:
```
tap,id=tap0,fd=5,vhost=on,vhostfd=6
```

As vhost-net need root permission, we cannot always open it in vmwrapper:
```
ls -l /dev/vhost-net
crw-------. 1 root root 10, 238 Feb 21 00:28 /dev/vhost-net
```

The possible location is in `(s *FDServer) serveGet`, and pass both tapFD and vhostFD to vmwrapper which is my internal implementation without structure changes. In vmwrapper, check if the length of fd is `fdNum = 2*len(InterfaceDescription)`, if it is, the vhost fd can be: `vhost = fmt.Sprintf(",vhost=on,vhostfd=%d", fds[fdNum+desc.FdIndex])`

**Comment by jellonek** [comment]
Are you sure that this will work? Looking on https://www.linux-kvm.org/page/UsingVhost - note in first line is "As of September 2010, vhost is not included in any released tarballs, so you need the git version.".
What about passing (e.g. with cni-genie) two interfaces with two fds, how that would work with this proposed `fdNum = 2*len(...)`?

**Comment by keyingliu** [comment]
I tried it, at least the vm can be started and `vhost=on,vhostfd=6` is there, and had a look the code https://github.com/libvirt/libvirt/blob/master/src/qemu/qemu_hotplug.c#L1374, it also tried vhost.

for fds, if no vhost fd is added, the fds containers the FDs depends on the interface number, with vhost net, the code like:
```
for range fds {
  open vhost-net and get vhost FD
  append it to fds array
}
```
and then here double fds passed to vmwrapper, that's why the fd size should be double of the network interface, the total fd number is 2*len(InterfaceDescription):
```	
rights := syscall.UnixRights(fds...)
	return &fdHeader{
		Magic:    fdMagic,
		Command:  fdGetResponse,
		DataSize: uint32(len(info)),
		OobSize:  uint32(len(rights)),
		Key:      hdr.Key,
	}, info, rights, nil
```

**Comment by jellonek** [comment]
If that will not break multiple interfaces support and be available as an configuration option (global and per pod basing on annotations) - I'm fully for that.
So... I'm waiting for the code to review :)
