### ISSUE TITLE
What are the advantages and disadvantages of virtlet compared with ranchervm and kubevirt?

### ISSUE THREAD

**Issue by jamesxia20181001** [Mirantis/virtlet#871]
What are the advantages and disadvantages of virtlet compared with ranchervm and kubevirt?

**Comment by lukaszo** [comment]
We did comparission between Virtlet and Kubevirt https://www.mirantis.com/blog/kubevirt-vs-virtlet-comparison-better/ 
It was 9 months ago so for sure some things are different now. 

As for ranchervm I hear about it for the first time so no idea.
