### ISSUE TITLE
how to put VMs and libvirtd out of the container

### ISSUE THREAD

**Issue by stonewesley** [Mirantis/virtlet#873]
I need to setup other devices like GPU or something else with VM, it may be difficult to do that in a container.
After looking through the architecture(From https://docs.virtlet.cloud/dev/architecture/) and source code, I wonder if it is possible to remove the vms and libvirt out of container.
Are there any problems except the additional secure problems(From https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/vm-isolation.md#additional-security-measures, it is not a problem for us)?

**Comment by ivan4th** [comment]
Virtlet is designed in a way that this should be possible indeed, one problem being that no one has actually tried it for a long time, so you can indeed attempt this, but your mileage may vary.

**Comment by stonewesley** [comment]
Thx a lot. We'd like to post the progress later
