### ISSUE TITLE
virtlet.cloud/ubuntu/16.04

### ISSUE THREAD

**Issue by kishoreakhila** [Mirantis/virtlet#876]
Hi @lukaszo, 
I'm new to virtlet and I have been facing the ErrorImagePull for 16.04 and I was wondering if there's any way to resolve this? I am able to reach the image using wget (https://github.com/onap/multicloud-k8s/blob/master/kud/deployment_infra/playbooks/configure-virtlet.yml#L39). 

Here's some information: 
  Normal   Pulling         6m55s (x3 over 7m48s)   kubelet, localhost  pulling image "virtlet.cloud/ubuntu/16.04"
  Warning  Failed          6m52s (x3 over 7m41s)   kubelet, localhost  Failed to pull image "virtlet.cloud/ubuntu/16.04": rpc error: code = Unknown desc = Error response from daemon: error parsing HTTP 404 response body: no error details found in HTTP response body: "{\"error\":\"Not Found\"}"
  Warning  Failed          6m52s (x3 over 7m41s)   kubelet, localhost  Error: ErrImagePull
  Warning  Failed          6m43s (x4 over 7m33s)   kubelet, localhost  Error: ImagePullBackOff

**Comment by lukaszo** [comment]
Hey @kishoreakhila 

can you show output of ```kubectl get configmap -n kube-system virtlet-image-translations``` ? It looks like there is some issue with configuration of image translation and virtlet is trying to get http://virtlet.cloud/ubuntu/16.04 directly which of course doesn't work.

**Comment by kishoreakhila** [comment]
Oh yeah, I wasn't understanding why it wasn't prepending https://ubuntu.... to pull the image. 
kubectl get configmap -n kube-system virtlet-image-translations
NAME                         DATA   AGE
virtlet-image-translations   1      24h
This is all I got from running the command you asked me to. Please let me know if there's more information you'd want me to furnish.

**Comment by lukaszo** [comment]
Ah, sorry. `kubectl get configmap -n kube-system virtlet-image-translations -o yaml` we need to see what's inside.

**Comment by kishoreakhila** [comment]
apiVersion: v1
data:
  images.yaml: |
    # BEGIN ANSIBLE MANAGED BLOCK
    translations:
      - name: ubuntu/14.04
        url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
      - name: ubuntu/16.04
        url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
      - name: ubuntu/18.04
        url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
      - regexp: 'centos/(\d+)-(\d+)'
        url: 'https://cloud.centos.org/centos/$1/images/CentOS-$1-x86_64-GenericCloud-$2.qcow2'
      - name: fedora
        url: https://dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2
    transports:
      "":
        proxy: "xxx"
    # END ANSIBLE MANAGED BLOCK
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"images.yaml":"# BEGIN ANSIBLE MANAGED BLOCK\ntranslations:\n  - name: ubuntu/14.04\n    url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img\n  - name: ubuntu/16.04\n    url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img\n  - name: ubuntu/18.04\n    url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img\n  - regexp: 'centos/(\\d+)-(\\d+)'\n    url: 'https://cloud.centos.org/centos/$1/images/CentOS-$1-x86_64-GenericCloud-$2.qcow2'\n  - name: fedora\n    url: https://dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2\ntransports:\n  \"\":\n    proxy: \xxx \"\n# END ANSIBLE MANAGED BLOCK\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"virtlet-image-translations","namespace":"kube-system"}}
  creationTimestamp: 2019-04-23T21:28:31Z
  name: virtlet-image-translations
  namespace: kube-system
  resourceVersion: "992"
  selfLink: /api/v1/namespaces/kube-system/configmaps/virtlet-image-translations
  uid: be32b3bb-660e-11e9-9be0-a4bf0121cdd8

**Comment by kishoreakhila** [comment]
Thank you for helping me Łukasz, I appreciate it. Been trying to resolve this for a bit now.

**Comment by lukaszo** [comment]
Please format the output using \`\`\` \`\`\` https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by kishoreakhila** [comment]
``` 
apiVersion: v1
data:
images.yaml: |
# BEGIN ANSIBLE MANAGED BLOCK
translations:
- name: ubuntu/14.04
url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
- name: ubuntu/16.04
url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
- name: ubuntu/18.04
url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
- regexp: 'centos/(\d+)-(\d+)'
url: 'https://cloud.centos.org/centos/$1/images/CentOS-$1-x86_64-GenericCloud-$2.qcow2'
- name: fedora
url: https://dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2
transports:
"":
proxy: "xxx"
# END ANSIBLE MANAGED BLOCK
kind: ConfigMap
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"v1","data":{"images.yaml":"# BEGIN ANSIBLE MANAGED BLOCK\ntranslations:\n - name: ubuntu/14.04\n url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img\n - name: ubuntu/16.04\n url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img\n - name: ubuntu/18.04\n url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img\n - regexp: 'centos/(\d+)-(\d+)'\n url: 'https://cloud.centos.org/centos/$1/images/CentOS-$1-x86_64-GenericCloud-$2.qcow2'\n - name: fedora\n url: https://dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2\ntransports:\n "":\n proxy: \xxx "\n# END ANSIBLE MANAGED BLOCK\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"virtlet-image-translations","namespace":"kube-system"}}
creationTimestamp: 2019-04-23T21:28:31Z
name: virtlet-image-translations
namespace: kube-system
resourceVersion: "992"
selfLink: /api/v1/namespaces/kube-system/configmaps/virtlet-image-translations
uid: be32b3bb-660e-11e9-9be0-a4bf0121cdd8
```

**Comment by lukaszo** [comment]
It looks like you configured your cluster in a wrong way. Are CRIProxy and Kubelet configured correctly to use Virtlet? Virtlet is not trying to download the image but  Docker.

**Comment by kishoreakhila** [comment]
Hi, @lukaszo apologies for the delayed response. I was away. Will reset my cluster and get back to you. Thank you for helping look into this.
