### ISSUE TITLE
Can't find containers of virtlet-cfr pod

### ISSUE THREAD

**Issue by changyi2409** [Mirantis/virtlet#878]
Hi,
I used the virtlet demo.sh to deloy one demo cluster with two nodes for cirros vm running. The system is work fine. But I can't find related containers of virtlet-cfr72 pod both in worker node. It seems that there is only k8s related containers in worker node.

root@kube-master:~# kubectl get nodes
NAME          STATUS   ROLES    AGE     VERSION
kube-master   Ready    master   6d22h   v1.13.0
kube-node-1   Ready    <none>   6d21h   v1.13.0

root@kube-master:~# kubectl get pod -n kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-86c58d9df4-whwrn                1/1     Running   0          6d22h
etcd-kube-master                        1/1     Running   1          6d22h
kube-apiserver-kube-master              1/1     Running   1          6d22h
kube-controller-manager-kube-master     1/1     Running   1          6d21h
kube-proxy-5rv6d                        1/1     Running   0          6d22h
kube-proxy-bgrvq                        1/1     Running   1          6d22h
kube-scheduler-kube-master              1/1     Running   1          6d21h
kubernetes-dashboard-769df5545f-cq7xh   1/1     Running   0          6d22h
virtlet-cfr72                           3/3     Running   1          6d21h

root@kube-master:~# kubectl describe pod virtlet-cfr72 -n kube-system
Name:               virtlet-cfr72
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               kube-node-1/10.192.0.3
...

root@kube-node-1:/var/lib# docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
a0965c44ac7f        gcr.io/google_containers/kubernetes-dashboard-amd64   "/dashboard --port=9…"   6 days ago          Up 6 days                               k8s_kubernetes-dashboard_kubernetes-dashboard-769df5545f-cq7xh_kube-system_e8999c8b-6a69-11e9-b6ca-367fafc6230c_0
e058736d09be        k8s.gcr.io/coredns                                    "/coredns -conf /etc…"   6 days ago          Up 6 days                               k8s_coredns_coredns-86c58d9df4-whwrn_kube-system_e89988e9-6a69-11e9-b6ca-367fafc6230c_0
e696dcef19df        k8s.gcr.io/pause:3.1                                  "/pause"                 6 days ago          Up 6 days                               k8s_POD_coredns-86c58d9df4-whwrn_kube-system_e89988e9-6a69-11e9-b6ca-367fafc6230c_0
a1624c2a9d28        k8s.gcr.io/pause:3.1                                  "/pause"                 6 days ago          Up 6 days                               k8s_POD_kubernetes-dashboard-769df5545f-cq7xh_kube-system_e8999c8b-6a69-11e9-b6ca-367fafc6230c_0
a0df02310356        eca69a070500                                          "/usr/local/bin/kube…"   6 days ago          Up 6 days                               k8s_kube-proxy_kube-proxy-5rv6d_kube-system_be55853d-6a69-11e9-8c22-367fafc6230c_1
797516fd0fa3        k8s.gcr.io/pause:3.1                                  "/pause"                 6 days ago          Up 6 days                               k8s_POD_kube-proxy-5rv6d_kube-system_be55853d-6a69-11e9-8c22-367fafc6230c_1

**Comment by changyi2409** [comment]
Is there any guideline for users to update the image url links?  Update the configmap yaml and recreate configmap and virtlet Pod to enable new image translation links?

Following is the default image links for virlet image translation. 

root@kube-master:~# kubectl get configmap -n kube-system virtlet-image-translations -o yaml
apiVersion: v1
data:
  demo_images.yaml: |
    translations:
      - name: cirros
        url: https://github.com/mirantis/virtlet/releases/download/v0.9.3/cirros.img
      - name: fedora
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2
kind: ConfigMap
metadata:
  creationTimestamp: "2019-04-29T10:32:25Z"
  name: virtlet-image-translations
  namespace: kube-system
  resourceVersion: "829"
  selfLink: /api/v1/namespaces/kube-system/configmaps/virtlet-image-translations
  uid: 144b1554-6a6a-11e9-b6ca-367fafc6230c

**Comment by jellonek** [comment]
Yep, exactly. Actually virtlet is loading translations [config](https://docs.virtlet.cloud/reference/images/#translation-configs) (from config map and from CRDs) only once, at the start, so after updating values in CRD or config map - operator needs to recreate all virtlet pods instances (on all nodes), what can be done using e.g.:
```bash
kubectl -n kube-system delete pods --all -l runtime=virtlet
```

**Comment by jellonek** [comment]
Ups. This info was incorrect - translation configuration (combined from crd and configmap files) should be reloaded on each pod definition, so there should be no need to kill existing instances of virtlet pods.
