### ISSUE TITLE
Missing files or instructions

### ISSUE THREAD

**Issue by vgopal** [Mirantis/virtlet#883]
(https://docs.virtlet.cloud/user-guide/real-cluster/)

After that, you need to get virtletctl command line tool (replace N.N.N in the command below accordingly):

curl -SL -o virtletctl https://github.com/Mirantis/virtlet/releases/download/vN.N.N/virtletctl

There is no such link found.

**Comment by lukaszo** [comment]
as described you should replace `N.N.N` with virtlet version which you are using. For example for version 1.5.1 it will be https://github.com/Mirantis/virtlet/releases/download/v1.5.1/virtletctl

**Comment by vgopal** [comment]
I tried https://github.com/Mirantis/virtlet/releases/download/v1.11.6/virtletctl wont it be easy there some listing or list of binaries available instead of guessing.

**Comment by pigmej** [comment]
@vgopal the listing is: https://github.com/Mirantis/virtlet/releases so no guessing needed :)
