### ISSUE TITLE
Example for a working windows 7/10 qcow2 image or description how to create a working windows7/10 qcow2 image

### ISSUE THREAD

**Issue by dmuiX** [Mirantis/virtlet#898]
Could someone provide a working example of a windows 7 VM? Or maybe an description how to provide a working windows 7 qcow2 image with the correct drivers installed?

The 2012 Server that is provided in this blog entry is working: 
https://www.mirantis.com/blog/virtlet-run-vms-as-kubernetes-pods
I have installed Windows 7 in a VM, that is working in KVM, but it is always throwing the bluescreen error 0x00000007b if I try to boot it in virtlet. ![Bluescreen](https://user-images.githubusercontent.com/19862760/64024764-6df82a00-cb3b-11e9-8c80-a45e9620c65b.png)
This error is showing, that the Boot medium is missing. So I think it has something todo with missing drivers. Which protokoll is virtlet using by default? Virtio SCSI? SCSI? And how can I install these drivers in Windows 7?

Thanks a lot & Kind Regards

**Comment by pigmej** [comment]
Hello, the easiest way is to get: https://cloudbase.it/windows-cloud-images and yes the drivers are Virtio.

**Comment by Sparklight77** [comment]
Hello

**Comment by ghost** [comment]
Hello wow are you

**Comment by Sparklight77** [comment]
Bro is replying on a 6y ago issue lmfao
