### ISSUE TITLE
How to expose service hosted in VM

### ISSUE THREAD

**Issue by GOVYANSONG** [Mirantis/virtlet#904]
This is a question on how to expose a service hosted inside VM. Is there any documentation explaining this subject? Thanks in advance.

**Comment by GOVYANSONG** [comment]
From example given at https://www.mirantis.com/blog/virtlet-run-vms-as-kubernetes-pods/, it seems that a service manifest is sufficient for virtlet to expose service hosted within Windows VM.

**Comment by jellonek** [comment]
There is no need to "expose" anything from VM. Any listening in VM port can be used as a port in kubernetes service.
