### ISSUE TITLE
How to access persistent volume from guest Windows VM

### ISSUE THREAD

**Issue by GOVYANSONG** [Mirantis/virtlet#905]
Currently, we run samba service on the host Linux and map samba share as network drive on guest Windows VM. We are aware of emerging approaches such as virtio-Fs in the upcoming Linux 5.4. So, how would guest Windows VM access persistent volume with virtlet? Please share your thoughts.

**Comment by jellonek** [comment]
PTAL on https://docs.virtlet.cloud/reference/volumes/#persistent-root-filesystem

**Comment by GOVYANSONG** [comment]
@jellonek , thanks for the link. Here is a follow up question: does virtlet support pod volume and container volume mount for windows guest VM? If so, how is mount path specified? For example, if I want vogue to be mounted at c:\temp, do I specify it in container definition as /c/temp? Thanks for your assistance.

**Comment by jellonek** [comment]
Dunno how cloud-init for windows works with that. TAL on https://cloudbase-init.readthedocs.io/en/latest/index.html but I'm assuming that only block devices will be working (raw devices or flex volumes prepared by virtlet) but probably you will need to handle them using user script and they will be usable as d: or under next available device name.

**Comment by GOVYANSONG** [comment]
@jellonek really appreciated your response. I will read more about cloud-Init. But during meantime, could you clarify on a possible solution to share data between virtlet VM pod and normal K8s pod?

**Comment by GOVYANSONG** [comment]
now, Take Ceph as an example. K8S document states that Ceph RBD is not RWX. To share data between pods running concurrently, CephFS needs to be used.
