### ISSUE TITLE
How to build virtlet from the source code?

### ISSUE THREAD

**Issue by libbylg** [Mirantis/virtlet#911]
I am try to compile the virtlet from the source code.
But I can not found any informations.
Is there some guide?

**Comment by lukaszo** [comment]
see https://github.com/Mirantis/virtlet/blob/master/docs/docs/dev/build-tool.md

**Comment by leyao-daily** [comment]
what you need is just a network env and make your own change, then
```
cd %{your_virtlet_repo}
./build/cmd.sh build 
```
When rebuilding, exec './build/cmd.sh clean' before build
