### ISSUE TITLE
Provide possibility to pass loglevel to binaries in containers

### ISSUE THREAD

**Issue by jellonek** [Mirantis/virtlet#92]
If we want to use different log levels (we should start doing that ASAP) - we also should have a possibility to change this loglevel values (if it should be set), per container (separately for virtlet, separately for libvirt) in manner close to passing cleanup request.

This requires passing variables through `docker-compose` what we have probably badly done in cleanup case.

**Comment by ivan4th** [comment]
Closed by #112 perhaps?

**Comment by jellonek** [comment]
Yes, exactly.
